Repository MTES-MCT/dialog, pull requests merged in 2022-11, with the labels that each got.

#9 Add ADR template
  adr/_template.md
Labels: documentation, adr

#8 adr: MCD
  adr/002_mcd.md
Labels: adr

#7 core: technical stack proposition
  .env
  .gitignore
  .php-cs-fixer.dist.php
  Makefile
  README.md
  adr/003_technical_stack.md
  bin/console
  composer.json
  composer.lock
  config/bundles.php
  config/packages/cache.yaml
  config/packages/framework.yaml
  config/packages/routing.yaml
  config/preload.php
  config/routes.yaml
  config/routes/framework.yaml
  config/services.yaml
  docker-compose.yml
  docker/Dockerfile
  public/index.php
  src/Controller/.gitignore
  src/Kernel.php
  symfony.lock
Labels: tech

#11 ADR: Add decision document for 'Format d'échange de données'
  adr/001_exchangeformat.md
  adr/_template.md
Labels: adr

#19 Ajout de Doctrine
  .env
  Makefile
  composer.json
  composer.lock
  config/bundles.php
  config/packages/doctrine.yaml
  config/packages/doctrine_migrations.yaml
  config/services.yaml
  src/Domain/.gitkeep
  src/Infrastructure/Persistence/Doctrine/Mapping/.gitkeep
  src/Infrastructure/Persistence/Doctrine/Migrations/.gitkeep
  symfony.lock
Labels: tech

#18 Improve documentation
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/adr/002_mcd.md
  docs/adr/003_technical_stack.md
  docs/adr/_template.md
  docs/deployment.md
  docs/spec/datex2/DATEXII_3_Common.xsd
  docs/spec/datex2/DATEXII_3_CommonExtension.xsd
  docs/spec/datex2/DATEXII_3_D2Payload.xsd
  docs/spec/datex2/DATEXII_3_Facilities.xsd
  docs/spec/datex2/DATEXII_3_LocationExtension.xsd
  docs/spec/datex2/DATEXII_3_LocationReferencing.xsd
  docs/spec/datex2/DATEXII_3_Parking.xsd
  docs/spec/datex2/DATEXII_3_TrafficRegulation.xsd
  docs/spec/datex2/example.xml
  docs/tools.md
Labels: documentation

#21 Ajout de documentation
  Makefile
  docs/README.md
  docs/adr/001_exchangeformat.md
  docs/adr/README.md
  docs/tools.md
Labels: documentation

#22 Adr sur l'architecture hexagonale
  docs/adr/002_mcd.md
  docs/adr/003_technical_stack.md
  docs/adr/004_hexagonal_architecture.md
  docs/adr/README.md
Labels: documentation

#23 Ajout des entités User & Organization
  .env.test
  .github/workflows/ci.yml
  .gitignore
  Makefile
  bin/phpunit
  composer.json
  composer.lock
  docs/tools.md
  phpunit.xml.dist
  src/Application/.gitkeep
  src/Domain/User/Organization.php
  src/Domain/User/Repository/OrganizationRepositoryInterface.php
  src/Domain/User/Repository/UserRepositoryInterface.php
  src/Domain/User/User.php
  src/Infrastructure/Persistence/Doctrine/Mapping/.gitkeep
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Organization.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/User.User.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/.gitkeep
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20221117141636.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/OrganizationRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/UserRepository.php
  symfony.lock
  tests/Unit/Domain/User/OrganizationTest.php
  tests/Unit/Domain/User/UserTest.php
  tests/bootstrap.php
Labels: tech

#26 Add PHPStan & postdeploy scripts to run doctrine migrations on scalingo
  .github/workflows/ci.yml
  Makefile
  composer.json
  composer.lock
  docs/tools.md
  scripts/postdeploy.sh
Labels: tech

#27 Change docker configuration
  Makefile
  docker-compose.yml
  docker/nginx/default.conf
  docker/php/Dockerfile
  docker/php/php.ini
Labels: tech

#29 Automaticaly run doctrine migrations on deploy
  Procfile
  scripts/postdeploy.sh
Labels: tech

#30 Add code coverage
  .github/workflows/ci.yml
  README.md
Labels: tech

#37 Add Symfony Messenger & Validator components to init CQRS
  .env
  composer.json
  composer.lock
  config/packages/messenger.yaml
  config/packages/validator.yaml
  config/services.yaml
  phpunit.xml.dist
  src/Application/.gitkeep
  src/Application/CommandBusInterface.php
  src/Application/CommandInterface.php
  src/Application/QueryBusInterface.php
  src/Application/QueryInterface.php
  src/Infrastructure/Adapter/CommandBus.php
  src/Infrastructure/Adapter/QueryBus.php
  symfony.lock
Labels: tech

#36 Add TrafficRegulation & RegulationCondition models
  src/Domain/TrafficRegulation/Enum/TrafficRegulationType.php
  src/Domain/TrafficRegulation/RegulationCondition.php
  src/Domain/TrafficRegulation/TrafficRegulation.php
  src/Infrastructure/Persistence/Doctrine/Mapping/TrafficRegulation.RegulationCondition.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/TrafficRegulation.TrafficRegulation.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20221122162137.php
  tests/Unit/Domain/RegulationOrder/RegulationOrderRecordTest.php
  tests/Unit/Domain/TrafficRegulation/RegulationConditionTest.php
  tests/Unit/Domain/TrafficRegulation/TrafficRegulationTest.php
Labels: tech

#39 Add VehicleCharacteristics model
  .github/workflows/ci.yml
  docs/spec/datex2/DATEXII_3_Common.xsd
  src/Domain/RegulationOrder/Enum/RegulationOrderRecordStatusEnum.php
  src/Domain/RegulationOrder/RegulationOrderRecord.php
  src/Domain/TrafficRegulation/Condition/Enum/VehicleCritairEnum.php
  src/Domain/TrafficRegulation/Condition/Enum/VehicleTypeEnum.php
  src/Domain/TrafficRegulation/Condition/Enum/VehicleUsageEnum.php
  src/Domain/TrafficRegulation/Condition/VehicleCharacteristics.php
  src/Domain/TrafficRegulation/Enum/TrafficRegulationEnum.php
  src/Domain/TrafficRegulation/RegulationCondition.php
  src/Domain/TrafficRegulation/TrafficRegulation.php
  src/Infrastructure/Persistence/Doctrine/Mapping/TrafficRegulation.Condition.VehicleCharacteristics.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/TrafficRegulation.RegulationCondition.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20221123133702.php
  tests/Unit/Domain/RegulationOrder/RegulationOrderRecordTest.php
  tests/Unit/Domain/TrafficRegulation/Condition/VehicleCharacteristicsTest.php
  tests/Unit/Domain/TrafficRegulation/RegulationConditionTest.php
  tests/Unit/Domain/TrafficRegulation/TrafficRegulationTest.php
Labels: tech

#47 Revamp Make usage
  .env.ci
  .github/workflows/ci.yml
  .gitignore
  Makefile
  docker/php/Dockerfile
  docs/tools.md
Labels: tech
