Repository MTES-MCT/dialog, pull requests merged in 2023-12, with the labels that each got.

#560 Fix form Time type
  assets/styles/app.scss
  src/Infrastructure/Form/Regulation/PeriodFormType.php
  src/Infrastructure/Form/Regulation/TimeSlotFormType.php
  templates/common/form/dsfr_theme.html.twig
  templates/regulation/fragments/_location_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateLocationControllerTest.php
  tests/e2e/pages/regulation_order.page.js
  tests/e2e/regulation_edit.spec.js
  translations/messages.fr.xlf
Labels: Bug

#546 Access request
  config/validator/Application/User/SaveAccessRequestCommand.xml
  config/validator/Domain/User/AccessRequest.xml
  src/Application/PasswordHasherInterface.php
  src/Application/StringUtilsInterface.php
  src/Application/User/Command/ConvertAccessRequestToUserCommand.php
  src/Application/User/Command/ConvertAccessRequestToUserCommandHandler.php
  src/Application/User/Command/SaveAccessRequestCommand.php
  src/Application/User/Command/SaveAccessRequestCommandHandler.php
  src/Domain/User/AccessRequest.php
  src/Domain/User/Exception/AccessAlreadyRequestedException.php
  src/Domain/User/Exception/AccessRequestNotFoundException.php
  src/Domain/User/Exception/SiretMissingException.php
  src/Domain/User/Exception/UserAlreadyRegisteredException.php
  src/Domain/User/Repository/AccessRequestRepositoryInterface.php
  src/Domain/User/Repository/OrganizationRepositoryInterface.php
  src/Domain/User/Repository/UserRepositoryInterface.php
  src/Domain/User/Specification/IsAccessAlreadyRequested.php
  src/Infrastructure/Adapter/PasswordHasher.php
  src/Infrastructure/Adapter/StringUtils.php
  src/Infrastructure/Controller/AccessRequestController.php
  src/Infrastructure/Controller/Admin/AccessRequestCrudController.php
  src/Infrastructure/Controller/Admin/DashboardController.php
  src/Infrastructure/Form/User/AccessRequestFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/AccessRequestFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.AccessRequest.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20231120081623.php
  src/Infrastructure/Persistence/Doctrine/Repository/Organization/OrganizationRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/AccessRequestRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/UserRepository.php
  templates/accessRequest.html.twig
  templates/common/header.html.twig
  templates/landing_authorities.html.twig
  templates/login.html.twig
  tests/Integration/Infrastructure/Controller/AccessRequestControllerTest.php
  tests/Integration/Infrastructure/Controller/Admin/AccessRequestCrudControllerTest.php
  tests/Integration/Infrastructure/Controller/LandingAuthoritiesControllerTest.php
  tests/Unit/Application/User/Command/ConvertAccessRequestToUserCommandHandlerTest.php
  tests/Unit/Application/User/Command/SaveAccessRequestCommandHandlerTest.php
  tests/Unit/Domain/User/AccessRequestTest.php
  tests/Unit/Infrastructure/Adapter/StringUtilsTest.php
  translations/messages.fr.xlf
Labels: REVIEW-1

#568 Fix display daily range days
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  templates/regulation/_period.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetLocationControllerTest.php
  translations/messages.fr.xlf
Labels: Bug

#569 Add fr_city table
  Makefile
  config/packages/doctrine.yaml
  data/.gitignore
  data/fr_city.sql
  docs/adr/002_mcd.md
  docs/tools/data.md
  package.json
  src/Domain/Country/France/City.php
  src/Domain/Country/France/Repository/CityRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/DBAL/CustomPostgreSQLPlatformService.php
  src/Infrastructure/Persistence/Doctrine/DBAL/CustomPostgreSQLSchemaManager.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Country.France.City.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20231205160304.php
  src/Infrastructure/Persistence/Doctrine/Repository/Country/France/CityRepository.php
  src/Infrastructure/Symfony/Command/LoadFrCityDataCommand.php
  tests/Integration/Infrastructure/Symfony/Command/DatabaseValidateCommandTest.php
  tests/Integration/Infrastructure/Symfony/Command/LoadFrCityDataCommandTest.php
  tests/Unit/Domain/Country/France/CityTest.php
  tools/mkfrcitysql
Labels: TYPE - Tech

#574 Fix deployment, move all deployment commands to Makefile
  Makefile
  Procfile
  package.json
  scripts/postdeploy.sh
  tools/mkfrcitysql
  tools/mkfrcitysql.php
Labels: Bug

#579 Split app.scss into modules
  assets/styles/app.scss
  assets/styles/components/authorities.scss
  assets/styles/components/autocomplete.scss
  assets/styles/components/box.css
  assets/styles/components/card.css
  assets/styles/components/dsfr-extensions/button.css
  assets/styles/components/dsfr-extensions/container.css
  assets/styles/components/dsfr-extensions/fieldset.css
  assets/styles/components/dsfr-extensions/icon.scss
  assets/styles/components/dsfr-extensions/index.scss
  assets/styles/components/form.css
  assets/styles/components/index.scss
  assets/styles/components/landing-diagram.css
  assets/styles/components/list.css
  assets/styles/components/regulation/index.scss
  assets/styles/components/regulation/table.scss
  assets/styles/components/regulation/timeslot.css
  assets/styles/components/regulation/vehicles.css
  assets/styles/defaults.css
  assets/styles/layouts/index.scss
  assets/styles/layouts/stack.css
  assets/styles/reset.css
  assets/styles/utilities/a11y.css
  assets/styles/utilities/dsfr-extensions/background.css
  assets/styles/utilities/dsfr-extensions/display.css
  assets/styles/utilities/dsfr-extensions/index.scss
  assets/styles/utilities/dsfr-extensions/sizing.css
  assets/styles/utilities/dsfr-extensions/text.css
  assets/styles/utilities/index.scss
  assets/styles/variables.css
  templates/index.html.twig
  templates/landing_authorities.html.twig
  templates/landing_digital_services.html.twig
  templates/landing_road_users.html.twig
  templates/regulation/create.html.twig
  templates/regulation/detail.html.twig
Labels: TYPE - Tech, refactor

#584 Migre la dernière localisation avec géométrie mais sans roadName
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20231227133838.php
Labels: Bug

#580 Use command instead of EudonetParisLocationItem
  src/Application/EudonetParis/Command/ImportEudonetParisRegulationCommand.php
  src/Application/EudonetParis/Command/ImportEudonetParisRegulationCommandHandler.php
  src/Application/Regulation/Command/SaveRegulationLocationCommand.php
  src/Domain/EudonetParis/EudonetParisLocationItem.php
  src/Infrastructure/EudonetParis/EudonetParisTransformer.php
  tests/Unit/Application/EudonetParis/Command/ImportEudonetParisRegulationCommandHandlerTest.php
  tests/Unit/Infrastructure/EudonetParis/EudonetParisTransformerTest.php
Labels: TYPE - Tech, refactor
