Repository MTES-MCT/dialog, pull requests merged in 2023-01, with the labels that each got.

#76 Add pgAdmin4
  docker-compose.yml
  docs/tools.md
Labels: tech

#92 Tools documenration reorganization
  docs/README.md
  docs/deployment/README.md
  docs/tools.md
  docs/tools/README.md
  docs/tools/db.md
  docs/tools/docker.md
  docs/tools/languages.md
  docs/tools/monitoring.md
  docs/tools/quality.md
Labels: documentation

#93 Update dependencies
  Makefile
  composer.lock
  docs/tools/languages.md
  package-lock.json
Labels: tech

#94 Add adr/005_geocoding.md
  docs/adr/005_geocoding.md
Labels: adr

#98 Implement form navigation controls
  src/Infrastructure/Controller/Regulation/Steps/Step2Controller.php
  src/Infrastructure/Controller/Regulation/Steps/Step3Controller.php
  src/Infrastructure/Controller/Regulation/Steps/Step4Controller.php
  templates/base.html.twig
  templates/regulation/steps/step1.html.twig
  templates/regulation/steps/step2.html.twig
  templates/regulation/steps/step3.html.twig
  templates/regulation/steps/step4.html.twig
  templates/regulation/steps/step5.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step1ControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step2ControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step3ControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step4ControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step5ControllerTest.php
  translations/messages.fr.xlf
Labels: correctif mineur

#104 Fix swapped coordinates
  docs/tools/services.md
  src/Domain/Geography/Coordinates.php
  src/Domain/Geography/GeometryFormatter.php
  src/Infrastructure/Adapter/APIAdresseGeocoder.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep2CommandHandlerTest.php
  tests/Unit/Domain/Condition/LocationTest.php
  tests/Unit/Domain/Geography/CoordinatesTest.php
  tests/Unit/Domain/Geography/GeometryFormatterTest.php
  tests/Unit/Infrastructure/Symfony/Command/GeocodeCommandTest.php
Labels: bug

#105 Prepare header for authentification
  templates/base.html.twig
  templates/common/header.html.twig
  tests/Integration/Infrastructure/Controller/LandingTest.php
  translations/messages.fr.xlf
Labels: mineur

#108 Update dependencies
  composer.lock
  package-lock.json
Labels: tech, mineur

#110 Add a limit to toHouseNumber and fromHouseNumber fields
  config/validator/Application/Regulation/Command/Steps/SaveRegulationStep2Command.xml
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step2ControllerTest.php
Labels: bug

#115 Add more form texts and tweaks
  assets/styles/app.scss
  config/validator/Application/Regulation/Command/Steps/SaveRegulationStep1Command.xml
  src/Application/Regulation/Command/Steps/SaveRegulationStep1Command.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep1CommandHandler.php
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/RegulationOrderListForDatexFormatView.php
  src/Domain/Regulation/RegulationOrder.php
  src/Infrastructure/Form/Regulation/Step1FormType.php
  src/Infrastructure/Form/Regulation/Step3FormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRepository.php
  templates/common/form/dsfr_theme.html.twig
  templates/regulation/steps/_stepper.html.twig
  templates/regulation/steps/base.html.twig
  templates/regulation/steps/step1.html.twig
  templates/regulation/steps/step2.html.twig
  templates/regulation/steps/step3.html.twig
  templates/regulation/steps/step4.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step1ControllerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep1CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep1CommandTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
  translations/messages.fr.xlf
Labels: mineur

#117 Move DSFR CSS imports to CSS bundle
  assets/styles/app.scss
  templates/base.html.twig
  webpack.config.js
Labels: tech, mineur

#118 Fix step5 checkbox label associations
  templates/regulation/steps/step5.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step5ControllerTest.php
Labels: bug, mineur
