Repository MTES-MCT/dialog, pull requests merged in 2023-05, with the labels that each got.

#305 Simplify confirmation modals
  assets/controllers/form_submit_controller.js
  templates/common/confirmation_modal.html.twig
  templates/regulation/_delete_modal.html.twig
  templates/regulation/_items.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_location_delete_form.html.twig
  templates/regulation/index.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  translations/messages.fr.xlf
Labels: refactor

#300 Setup E2E tests using Playwright
  .github/workflows/ci.yml
  .gitignore
  Makefile
  docker-compose.yml
  docs/tools/quality.md
  package-lock.json
  package.json
  playwright.config.js
  templates/regulation/_items.html.twig
  tests/e2e/auth.setup.js
  tests/e2e/list.spec.js
  translations/messages.fr.xlf
Labels: TYPE - Tech, REVIEW-1

#311 Fix the confirm box display
  templates/base.html.twig
Labels: bug

#309 Duplicate from regulation detail page
  templates/regulation/detail.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
Labels: REVIEW-1

#303 Duplication regulation locations
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
Labels: REVIEW-1

#310 Display Symfony error responses instead of "Content missing"
  assets/bootstrap.js
  assets/lib.js
Labels: TYPE - Tech

#315 Display address parsing error
  config/validator/Application/Regulation/Command/SaveRegulationLocationCommand.xml
  src/Infrastructure/Validator/SaveRegulationGeneralInfoCommandConstraintValidator.php
  src/Infrastructure/Validator/ValidAddressConstraint.php
  src/Infrastructure/Validator/ValidAddressConstraintValidator.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddLocationControllerTest.php
  tests/Unit/Infrastructure/Validation/SaveRegulationOrderCommandConstraintValidatorTest.php
  translations/validators.fr.xlf
Labels: bug, REVIEW-1

#316 Add missing translation keys
  templates/regulation/detail.html.twig
Labels: REVIEW-1

#319 Fix form error handling in AddRegulationController
  src/Infrastructure/Controller/Regulation/AddRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/SaveGeneralInfoController.php
  src/Infrastructure/Form/Regulation/GeneralInfoFormType.php
  templates/regulation/_general_info_form.html.twig
  templates/regulation/create.html.twig
  templates/regulation/fragments/_general_info_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
Labels: bug, refactor

#320 correction bugs affichage
  assets/styles/app.scss
  templates/regulation/_general_info_form.html.twig
  templates/regulation/fragments/_location_delete_form.html.twig
  templates/regulation/fragments/_location_form.html.twig
Labels: REVIEW-2

#322 Fix page title for permanent regulation orders
  templates/regulation/detail.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  translations/messages.fr.xlf
Labels: ui

#313 Add, edit and display measure's type to locations
  assets/controllers/form_collection_controller.js
  assets/styles/app.scss
  config/validator/Application/Regulation/Command/SaveMeasureCommand.xml
  config/validator/Application/Regulation/Command/SaveRegulationLocationCommand.xml
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Command/SaveMeasureCommand.php
  src/Application/Regulation/Command/SaveMeasureCommandHandler.php
  src/Application/Regulation/Command/SaveRegulationLocationCommand.php
  src/Application/Regulation/Command/SaveRegulationLocationCommandHandler.php
  src/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandler.php
  src/Application/Regulation/View/DetailLocationView.php
  src/Application/Regulation/View/MeasureView.php
  src/Domain/Regulation/Enum/MeasureTypeEnum.php
  src/Domain/Regulation/Location.php
  src/Domain/Regulation/Measure.php
  src/Domain/Regulation/Repository/MeasureRepositoryInterface.php
  src/Infrastructure/Form/Regulation/LocationFormType.php
  src/Infrastructure/Form/Regulation/MeasureFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MeasureFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/MeasureRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_location.html.twig
  templates/regulation/fragments/_location_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Unit/Application/Regulation/Command/SaveMeasureCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveRegulationLocationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandlerTest.php
  tests/Unit/Domain/Regulation/LocationTest.php
  tests/Unit/Domain/Regulation/MeasureTest.php
  tests/e2e/regulation_edit.spec.js
  translations/messages.fr.xlf
Labels: draft

#323 Fix coverage
  src/Infrastructure/Validator/ValidAddressConstraintValidator.php
  tests/Unit/Infrastructure/Validation/ValidAddressConstraintValidatorTest.php
Labels: TYPE - Tech

#324 Feat/husky
  .husky/_/husky.sh
  .husky/pre-commit
  Makefile
  docker/php/Dockerfile
  package-lock.json
  package.json
Labels: REVIEW-1

#325 Measures duplication
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  tests/Integration/Infrastructure/Controller/Regulation/DuplicateRegulationControllerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
Labels: REVIEW-1

#328 Init general form type with start date to tomorrow
  config/services.yaml
  src/Application/DateUtilsInterface.php
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommand.php
  src/Infrastructure/Adapter/DateUtils.php
  src/Infrastructure/Controller/Regulation/AddRegulationController.php
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Mock/DateUtilsMock.php
  tests/Unit/Infrastructure/Adapter/DateUtilsTest.php
Labels: REVIEW-1

#321 Use truncated description as general info block title
  composer.json
  composer.lock
  config/bundles.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  symfony.lock
  templates/regulation/_general_info_form.html.twig
  templates/regulation/fragments/_general_info.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetRegulationGeneralInfoControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/SaveRegulationGeneralInfoControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
Labels: ui

#329 Remove the notion of decorator useless in our case
  config/services.yaml
Labels: TYPE - Tech

#334 Update to SF 6.2.10 with tests corrections
  composer.lock
  config/packages/http_discovery.yaml
  package-lock.json
  src/Application/Regulation/View/RegulationOrderRecordSummaryView.php
  symfony.lock
  tests/SessionHelper.php
Labels: TYPE - Tech

#335 Add missing breadcrumb button for mobile
  templates/common/breadcrumb.html.twig
  translations/messages.fr.xlf
Labels: bug, ui

#332 Adjust list on mobile
  assets/styles/app.scss
  playwright.config.js
  templates/regulation/_items.html.twig
  templates/regulation/index.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/e2e/list.mobile.spec.js
  translations/messages.fr.xlf
Labels: ui

#333 Add sidebar to regulation add page
  assets/styles/app.scss
  templates/regulation/create.html.twig
  templates/regulation/detail.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
Labels: ui

#330 Display category in general info
  src/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandler.php
  src/Application/Regulation/View/RegulationOrderRecordSummaryView.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/_general_info_form.html.twig
  templates/regulation/fragments/_general_info.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetRegulationGeneralInfoControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandlerTest.php
  tests/e2e/general_info_form.spec.js
  translations/messages.fr.xlf
Labels: ui

#338 Remove datex link
  templates/regulation/index.html.twig
  translations/messages.fr.xlf
Labels: ux

#337 Add back link to regulation detail page
  templates/regulation/detail.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  translations/messages.fr.xlf
Labels: ux

#326 Mandatory restrictions and remove duplicate button from regulations list
  config/validator/Application/Regulation/Command/SaveRegulationGeneralInfoCommand.xml
  config/validator/Application/Regulation/Command/SaveRegulationLocationCommand.xml
  src/Application/Regulation/Command/PublishRegulationCommandHandler.php
  src/Infrastructure/Controller/Regulation/DuplicateRegulationController.php
  src/Infrastructure/Form/Regulation/LocationFormType.php
  templates/regulation/fragments/_location_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/DuplicateRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  translations/validators.fr.xlf
Labels: REVIEW-1

#341 Add speed limitation measure
  config/validator/Application/Regulation/Command/SaveMeasureCommand.xml
  src/Domain/Regulation/Enum/MeasureTypeEnum.php
  translations/messages.fr.xlf
Labels: REVIEW-1

#347 Change buttons order
  templates/regulation/fragments/_location.html.twig
Labels: ux

#351 Add noscript balise
  templates/base.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/DuplicateRegulationControllerTest.php
  translations/messages.fr.xlf
Labels: REVIEW-3, ux
