Repository MTES-MCT/dialog, pull requests merged in 2023-10, with the labels that each got.

#498 Add implementation maxSpeed Datex II & Word
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/DatexTrafficRegulationView.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MeasureFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/api/regulations.xml.twig
  templates/regulation/export.md.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
  translations/messages.fr.xlf
Labels: TYPE - Tech

#495 Add implementation hints
  .github/ISSUE_TEMPLATE/user-story.md
Labels: documentation

#501 Implement new MPD
  src/Domain/Condition/Period/DailyRange.php
  src/Domain/Condition/Period/Period.php
  src/Domain/Condition/Period/TimeSlot.php
  src/Domain/Regulation/Repository/DailyRangeRepositoryInterface.php
  src/Domain/Regulation/Repository/TimeSlotRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.DailyRange.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.Period.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.TimeSlot.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20231009122722.php
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20231010092809.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateLocationControllerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Period/SavePeriodCommandHandlerTest.php
  tests/Unit/Domain/Condition/Period/DailyRangeTest.php
  tests/Unit/Domain/Condition/Period/PeriodTest.php
  tests/Unit/Domain/Condition/Period/TimeSlotTest.php
Labels: TYPE - Tech

#508 Add missing contact translation in error pages
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  translations/messages.fr.xlf
Labels: bug, mineur

#511 Drop maxResults on datex query
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
Labels: bug, TYPE - Tech, EPIC - Publication

#514 Add tool to connect to remote Scalingo DB locally
  docs/tools/db.md
  docs/tools/eudonet_paris.md
  tools/scalingodbtunnel
Labels: documentation, TYPE - Tech

#517 Fix typo
  docs/tools/eudonet_paris.md
Labels: documentation
