Repository MTES-MCT/dialog, pull requests merged in 2023-06, with the labels that each got.

#360 Drop Condition model and fix period bug
  src/Application/Regulation/Command/Condition/DeletePeriodCommand.php
  src/Application/Regulation/Command/Condition/DeletePeriodCommandHandler.php
  src/Application/Regulation/Command/Condition/SavePeriodCommandHandler.php
  src/Application/Regulation/Command/SaveMeasureCommand.php
  src/Application/Regulation/Command/SaveMeasureCommandHandler.php
  src/Domain/Condition/Condition.php
  src/Domain/Condition/Period/Period.php
  src/Domain/Condition/VehicleCharacteristics.php
  src/Domain/Regulation/Measure.php
  src/Domain/Regulation/Repository/ConditionRepositoryInterface.php
  src/Domain/Regulation/Repository/PeriodRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MeasureFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Condition.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.Period.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.VehicleCharacteristics.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Measure.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230605140125.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/ConditionRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/PeriodRepository.php
  templates/common/form/dsfr_theme.html.twig
  templates/regulation/fragments/_location_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateLocationControllerTest.php
  tests/Unit/Application/Regulation/Command/Condition/DeletePeriodCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Condition/SavePeriodCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveMeasureCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveMeasureCommandTest.php
  tests/Unit/Domain/Condition/ConditionTest.php
  tests/Unit/Domain/Condition/Period/PeriodTest.php
  tests/Unit/Domain/Condition/VehicleCharacteristicsTest.php
  tests/Unit/Domain/Regulation/MeasureTest.php
  tests/e2e/regulation_edit.spec.js
Labels: REVIEW-1

#362 Update deps
  composer.lock
  config/bundles.php
  package-lock.json
  symfony.lock
Labels: TYPE - Tech, REVIEW-2

#363 Fix location form structure
  assets/controllers/form_collection_controller.js
  templates/regulation/fragments/_location_form.html.twig
  tests/e2e/regulation_edit.spec.js
Labels: REVIEW-1

#359 Display periods on location card
  config/validator/Application/Regulation/Command/SavePeriodCommand.xml
  src/Application/DateUtilsInterface.php
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Command/Period/DeletePeriodCommand.php
  src/Application/Regulation/Command/Period/DeletePeriodCommandHandler.php
  src/Application/Regulation/Command/Period/SavePeriodCommand.php
  src/Application/Regulation/Command/Period/SavePeriodCommandHandler.php
  src/Application/Regulation/Command/SaveMeasureCommand.php
  src/Application/Regulation/Command/SaveMeasureCommandHandler.php
  src/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandler.php
  src/Application/Regulation/View/DetailLocationView.php
  src/Application/Regulation/View/MeasureView.php
  src/Application/Regulation/View/PeriodView.php
  src/Domain/Condition/Period/Enum/ApplicableDayEnum.php
  src/Domain/Condition/Period/Period.php
  src/Domain/Regulation/Measure.php
  src/Domain/Regulation/RegulationOrderRecord.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Adapter/DateUtils.php
  src/Infrastructure/Form/Regulation/PeriodFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MeasureFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Location.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Measure.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230613123709.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/fragments/_location.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/DuplicateRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Mock/DateUtilsMock.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Period/DeletePeriodCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Period/SavePeriodCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Period/SavePeriodCommandTest.php
  tests/Unit/Application/Regulation/Command/SaveMeasureCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveMeasureCommandTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandlerTest.php
  tests/Unit/Domain/Condition/Period/Enum/ApplicableDayEnumTest.php
  tests/Unit/Domain/Condition/Period/PeriodTest.php
  tests/Unit/Domain/Regulation/MeasureTest.php
  tests/Unit/Domain/Regulation/RegulationOrderRecordTest.php
  tests/Unit/Infrastructure/Adapter/DateUtilsTest.php
  tests/e2e/regulation_edit.spec.js
  translations/messages.fr.xlf
Labels: REVIEW-1

#364 Allow to delete published regulation
  templates/regulation/detail.html.twig
Labels: bug

#361 Duplicate periods
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MeasureFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  templates/regulation/fragments/_location.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/DuplicateRegulationControllerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
Labels: REVIEW-1

#366 Add Johan account
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230615071803.php
Labels: TYPE - Tech

#370 Display restriction form by default when adding a new location
  src/Application/Regulation/Command/SaveRegulationLocationCommand.php
  tests/e2e/regulation_edit.spec.js
Labels: bug, ux

#368 Improve location form UX
  src/Infrastructure/Form/Regulation/MeasureFormType.php
  templates/regulation/fragments/_location_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateLocationControllerTest.php
  translations/messages.fr.xlf
  translations/validators.fr.xlf
Labels: bug, ux

#381 Fix svg rendering
  assets/styles/app.scss
Labels: bug, REVIEW-1

#389 Fix redis on production
  .env
  .env.ci
  .github/workflows/ci.yml
  config/packages/framework.yaml
  config/services.yaml
Labels: bug

#394 Handle possibly null vehicleTypes fields
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
Labels: bug

#395 Avoid error responses from APIAdresse on short searches
  src/Infrastructure/Adapter/APIAdresseGeocoder.php
  tests/Unit/Infrastructure/Adapter/APIAdresseGeocoderTest.php
Labels: bug

#387 Allow user to have many organizations
  src/Application/Regulation/Command/DeleteRegulationCommand.php
  src/Application/Regulation/Command/DeleteRegulationCommandHandler.php
  src/Application/Regulation/Command/DuplicateRegulationCommand.php
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Query/GetRegulationsQuery.php
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Application/Regulation/View/RegulationOrderListItemView.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Domain/Regulation/Specification/CanOrganizationAccessToRegulation.php
  src/Domain/User/User.php
  src/Infrastructure/Controller/Regulation/AbstractRegulationController.php
  src/Infrastructure/Controller/Regulation/AddRegulationController.php
  src/Infrastructure/Controller/Regulation/DeleteRegulationController.php
  src/Infrastructure/Controller/Regulation/DuplicateRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/SaveGeneralInfoController.php
  src/Infrastructure/Controller/Regulation/ListRegulationsController.php
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230626093821.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Security/Provider/UserProvider.php
  src/Infrastructure/Security/SymfonyUser.php
  templates/regulation/_items.html.twig
  tests/Integration/Infrastructure/Controller/AbstractWebTestCase.php
  tests/Unit/Application/Regulation/Command/DeleteRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
  tests/Unit/Domain/Regulation/Specification/CanOrganizationAccessToRegulationTest.php
  tests/Unit/Domain/User/UserTest.php
  tests/Unit/Infrastructure/Security/SymfonyUserTest.php
  translations/messages.fr.xlf
Labels: REVIEW-1

#391 Improve Redis configuration
  composer.json
  config/packages/framework.yaml
  docker/php/php.ini
Labels: REVIEW-1

#396 Fix empty regulations rendering
  templates/regulation/_items.html.twig
Labels: ui
