Repository MTES-MCT/dialog, pull requests merged in 2023-11, with the labels that each got.

#534 Passe l'ADR-007 en "ACCEPTÉ"
  docs/adr/007_eudonet_paris_integration.md
Labels: documentation

#550 Fix user stats
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/UserRepository.php
Labels: Bug

#555 Fix blog edit link
  blog/_includes/templates/footer.njk
Labels: Bug

#556 Remove newsletter link
  blog/_includes/templates/newsletter_and_follow_us.njk
Labels: Bug

#552 Add siret to organization
  config/validator/Domain/User/Organization.xml
  src/Domain/User/Organization.php
  src/Infrastructure/Controller/Admin/OrganizationCrudController.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Organization.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20231121092542.php
  tests/Unit/Domain/User/OrganizationTest.php
Labels: REVIEW-1
