Repository MTES-MCT/dialog, pull requests merged in 2023-09, with the labels that each got.

#466 Correction affichage liste vide sur mobile
  assets/styles/app.scss
  templates/regulation/_items.html.twig
Labels: bug, ui

#478 Drop target="_self" in navbar links
  templates/layouts/public.html.twig
Labels: bug

#484 Create controller for form reveal behavior
  assets/controllers/condition_controller.js
  assets/controllers/disable_controller.js
  assets/controllers/form_reveal_controller.js
  assets/controllers/visibility_controller.js
  templates/regulation/_general_info_form.html.twig
  templates/regulation/_vehicle_set_form.html.twig
  tests/e2e/pages/regulation_order.page.js
Labels: refactor

#485 Add docs: "Bien démarrer"
  docs/README.md
  docs/getting-started.md
  docs/tutorials/README.md
  docs/tutorials/datex2.md
Labels: documentation

#490 Update npm dependencies
  .github/workflows/ci.yml
  Makefile
  assets/styles/app.scss
  package-lock.json
  public/images/restriction/all_vehicles.no.svg
  public/images/restriction/all_vehicles.yes.svg
  templates/common/form/dsfr_theme.html.twig
  templates/login.html.twig
  templates/regulation/_vehicle_set_form.html.twig
  tests/e2e/pages/regulation_order.page.js
Labels: dependencies

#489 Simplify display of heavyweight characteristics
  src/Application/Regulation/View/VehicleSetView.php
  templates/regulation/_vehicle_set.html.twig
  tests/Unit/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandlerTest.php
  translations/messages.fr.xlf
Labels: refactor
