Repository MTES-MCT/dialog, pull requests merged in 2023-04, with the labels that each got.

#270 Translate breadcrumb titles explicitly
  templates/common/breadcrumb.html.twig
  templates/regulation/create.html.twig
  templates/regulation/detail.html.twig
Labels: bug

#275 Rename save repositories methods to add
  src/Application/Regulation/Command/SaveRegulationLocationCommandHandler.php
  src/Application/Regulation/Command/SaveRegulationOrderCommandHandler.php
  src/Domain/Regulation/Repository/LocationRepositoryInterface.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Domain/Regulation/Repository/RegulationOrderRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRepository.php
  tests/Unit/Application/Regulation/Command/SaveRegulationLocationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveRegulationOrderCommandHandlerTest.php
Labels: REVIEW-1

#272 Add localisations to regulation order list
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Application/Regulation/View/RegulationOrderListItemView.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrderRecord.orm.xml
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/_items.html.twig
  templates/regulation/index.html.twig
  tests/Integration/Infrastructure/Common/PaginationTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
  translations/messages.fr.xlf
Labels: bug, REVIEW-1

#278 Missing lint
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
Labels: bug

#276 Use turbo stream on location form
  src/Application/Regulation/Command/SaveRegulationLocationCommandHandler.php
  src/Infrastructure/Controller/Regulation/Fragments/AddLocationController.php
  src/Infrastructure/Controller/Regulation/Fragments/AddLocationLinkFragmentController.php
  src/Infrastructure/Controller/Regulation/Fragments/UpdateLocationController.php
  src/Infrastructure/Form/Regulation/LocationFormType.php
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_add_location_link.html.twig
  templates/regulation/fragments/_location.added.stream.html.twig
  templates/regulation/fragments/_location.html.twig
  templates/regulation/fragments/_location_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddLocationLinkFragmentControllerTest.php
  tests/Unit/Application/Regulation/Command/SaveRegulationLocationCommandHandlerTest.php
Labels: REVIEW-1

#293 Display house number fields side by side
  templates/regulation/fragments/_location_form.html.twig
Labels: REVIEW-1, ui

#299 Pagination using Doctrine paginator without custom count query
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Organization.orm.xml
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
Labels: REVIEW-1

#307 Fix regulation publication
  templates/regulation/detail.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
Labels: bug, TYPE - Tech, REVIEW-1
