Repository MTES-MCT/dialog, pull requests merged in 2023-08, with the labels that each got.

#431 Fix purging of fr-alert--* classes
  webpack.config.js
Labels: bug

#436 Address Doctrine deprecation warning about partial syntax
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Domain/User/Specification/DoesOrganizationAlreadyHaveRegulationOrderWithThisIdentifier.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Unit/Domain/User/Specification/DoesOrganizationAlreadyHaveRegulationOrderWithThisIdentifierTest.php
Labels: TYPE - Tech, refactor

#430 Improve deployment docs
  docs/deployment/README.md
  docs/deployment/scalingo-branch-check.png
  docs/tools/analytics.md
Labels: documentation

#445 Remove xdebug option to improve execution time
  Makefile
Labels: TYPE - Tech

#444 [CI] Fix composer cache directory deprecated message
  .github/workflows/ci.yml
Labels: TYPE - Tech

#437 Fix DATEX trafficRegulations output
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/DatexTrafficRegulationView.php
  src/Application/Regulation/View/RegulationOrderDatexListItemView.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MeasureFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/VehicleSetFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/api/regulations.xml.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/DeleteLocationFragmentControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
Labels: bug

#454 Add landing diagram
  assets/styles/app.scss
  public/images/landing/community.png
  public/images/landing/system.png
  templates/_landing_diagram.html.twig
  templates/landing_authorities.html.twig
  translations/messages.fr.xlf
Labels: ui

#458 Add missing empty case to GetRegulationOrdersToDatexFormatQueryHandler
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
Labels: bug

#459 Improve twig linter execution time
  Makefile
Labels: TYPE - Tech

#457 Refine landing diagram arrows
  assets/styles/app.scss
Labels: ui

#461 Document ecodesign referent
  templates/ecodesign_statement.html.twig
Labels: documentation

#462 Restrict admin access to Mathieu Fernandez
  .env
  config/services.yaml
  docs/deployment/README.md
  src/Application/Regulation/Command/SaveRegulationLocationCommandHandler.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OrganizationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/UserFixture.php
  src/Infrastructure/Security/Provider/UserProvider.php
  tests/Integration/Infrastructure/Controller/AbstractWebTestCase.php
  tests/Integration/Infrastructure/Controller/Admin/DashboardControllerTest.php
  tests/Integration/Infrastructure/Controller/Admin/OrganizationCrudControllerTest.php
  tests/Integration/Infrastructure/Controller/Admin/UserCrudControllerTest.php
  tests/Integration/Infrastructure/Controller/LandingControllerTest.php
  tests/Integration/Infrastructure/Controller/LoginControllerTest.php
Labels: TYPE - Tech
