Repository MTES-MCT/dialog, pull requests merged in 2023-03, with the labels that each got.

#192 Custom error pages
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  translations/messages.fr.xlf
Labels: TYPE - Tech

#218 Add startDate and endDate to RegulationOrder
  config/validator/Application/Regulation/Command/Steps/SaveRegulationStep1Command.xml
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep1Command.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep1CommandHandler.php
  src/Domain/Regulation/RegulationOrder.php
  src/Infrastructure/Form/Regulation/Steps/Step1FormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230313132443.php
  src/Infrastructure/Validator/SaveRegulationStep1CommandConstraint.php
  src/Infrastructure/Validator/SaveRegulationStep1CommandConstraintValidator.php
  templates/regulation/steps/step1.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step1ControllerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep1CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep1CommandTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
  tests/Unit/Infrastructure/Validation/SaveRegulationStep1CommandConstraintValidatorTest.php
  tests/Unit/Infrastructure/Validation/SaveRegulationStep3CommandConstraintValidatorTest.php
  translations/messages.fr.xlf
  translations/validators.fr.xlf
Labels: TYPE - Tech

#221 Fix formatDateTime timezone handling
  src/Infrastructure/Twig/AppExtension.php
  tests/Unit/Infrastructure/Twig/AppExtensionTest.php
Labels: bug

#220 Link Location to RegulationOrder
  src/Application/Condition/Query/Location/GetLocationByRegulationConditionQuery.php
  src/Application/Condition/Query/Location/GetLocationByRegulationConditionQueryHandler.php
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep2Command.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep2CommandHandler.php
  src/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandler.php
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Application/Regulation/Query/Location/GetLocationByRegulationOrderQuery.php
  src/Application/Regulation/Query/Location/GetLocationByRegulationOrderQueryHandler.php
  src/Application/Regulation/View/ListItemLocationView.php
  src/Application/Regulation/View/PeriodView.php
  src/Application/Regulation/View/RegulationOrderDatexListItemView.php
  src/Application/Regulation/View/RegulationOrderListItemView.php
  src/Application/Regulation/View/RegulationOrderRecordSummaryView.php
  src/Domain/Condition/RegulationCondition.php
  src/Domain/Condition/Repository/LocationRepositoryInterface.php
  src/Domain/Regulation/Factory/LocationFactory.php
  src/Domain/Regulation/Location.php
  src/Domain/Regulation/RegulationOrder.php
  src/Domain/Regulation/Repository/LocationRepositoryInterface.php
  src/Domain/Regulation/Specification/CanRegulationOrderRecordBePublished.php
  src/Infrastructure/Controller/Regulation/Steps/Step2Controller.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.RegulationCondition.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Location.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230314103748.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/api/regulations.xml.twig
  templates/regulation/_items.html.twig
  templates/regulation/_summary.html.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Unit/Application/Condition/Query/Location/GetLocationByRegulationConditionQueryHandlerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep2CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep2CommandTest.php
  tests/Unit/Application/Regulation/Location/GetLocationByRegulationOrderQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
  tests/Unit/Domain/Condition/RegulationConditionTest.php
  tests/Unit/Domain/Regulation/LocationTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
  tests/Unit/Domain/Regulation/Specification/CanRegulationOrderRecordBePublishedTest.php
Labels: TYPE - Tech

#226 Merge period entities
  src/Domain/Condition/Period/DayWeekMonth.php
  src/Domain/Condition/Period/Period.php
  src/Domain/Condition/Period/SpecialDay.php
  src/Domain/Condition/Period/TimePeriodOfDay.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.DayWeekMonth.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.Period.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.SpecialDay.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.TimePeriodOfDay.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230315135642.php
  tests/Unit/Domain/Condition/Period/DayWeekMonthTest.php
  tests/Unit/Domain/Condition/Period/PeriodTest.php
  tests/Unit/Domain/Condition/Period/SpecialDayTest.php
  tests/Unit/Domain/Condition/Period/TimePeriodOfDayTest.php
Labels: TYPE - Tech, REVIEW-2

#232 Migrate RegulationConditon model
  config/validator/Application/Regulation/Command/Steps/SaveRegulationStep4Command.xml
  src/Application/Condition/Query/VehicleCharacteristics/GetVehicleCharacteristicsByRegulationConditionQuery.php
  src/Application/Condition/Query/VehicleCharacteristics/GetVehicleCharacteristicsByRegulationConditionQueryHandler.php
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep1CommandHandler.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep4Command.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep4CommandHandler.php
  src/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandler.php
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/RegulationOrderDatexListItemView.php
  src/Application/Regulation/View/RegulationOrderRecordSummaryView.php
  src/Application/Regulation/View/VehicleCharacteristicsView.php
  src/Domain/Condition/ConditionSet.php
  src/Domain/Condition/Enum/OperatorEnum.php
  src/Domain/Condition/Period/Period.php
  src/Domain/Condition/RegulationCondition.php
  src/Domain/Condition/Repository/RegulationConditionRepositoryInterface.php
  src/Domain/Condition/Repository/VehicleCharacteristicsRepositoryInterface.php
  src/Domain/Regulation/Measure.php
  src/Domain/Regulation/RegulationOrder.php
  src/Infrastructure/Controller/Regulation/Steps/Step2Controller.php
  src/Infrastructure/Controller/Regulation/Steps/Step4Controller.php
  src/Infrastructure/Form/Regulation/Steps/Step4FormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationConditionFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/VehicleCharacteristicsFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.ConditionSet.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.Period.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.RegulationCondition.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Measure.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230321085532.php
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230321145142.php
  src/Infrastructure/Persistence/Doctrine/Repository/Condition/RegulationConditionRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Condition/VehicleCharacteristicsRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/api/regulations.xml.twig
  templates/regulation/_items.html.twig
  templates/regulation/_summary.html.twig
  templates/regulation/steps/step4.html.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step2ControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step4ControllerTest.php
  tests/Unit/Application/Condition/Query/VehicleCharacteristics/GetVehicleCharacteristicsByRegulationConditionQueryHandlerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep1CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep4CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep4CommandTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
  tests/Unit/Domain/Condition/ConditionSetTest.php
  tests/Unit/Domain/Condition/Period/PeriodTest.php
  tests/Unit/Domain/Condition/RegulationConditionTest.php
  tests/Unit/Domain/Regulation/MeasureTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
  translations/messages.fr.xlf
Labels: TYPE - Tech, REVIEW-1

#233 Rename RegulationCondition to Condition
  src/Application/Regulation/Command/Steps/SaveRegulationStep1CommandHandler.php
  src/Domain/Condition/Condition.php
  src/Domain/Condition/Period/Period.php
  src/Domain/Condition/VehicleCharacteristics.php
  src/Domain/Regulation/Measure.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Condition.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.Period.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.VehicleCharacteristics.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Measure.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230321170536.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep2CommandHandlerTest.php
  tests/Unit/Domain/Condition/Period/PeriodTest.php
  tests/Unit/Domain/Condition/RegulationConditionTest.php
  tests/Unit/Domain/Condition/VehicleCharacteristicsTest.php
  tests/Unit/Domain/Regulation/MeasureTest.php
Labels: TYPE - Tech, REVIEW-1

#236 Make AppExtensionTest independent of daylight saving time
  tests/Unit/Infrastructure/Twig/AppExtensionTest.php
Labels: TYPE - Tech, REVIEW-1

#238 Complete turbo drive config
  config/packages/webpack_encore.yaml
Labels: TYPE - Tech, REVIEW-1

#242 Add more security with login_throttling option
  composer.json
  composer.lock
  config/packages/security.yaml
Labels: TYPE - Tech, REVIEW-1

#244 Change login parameters name to improve login security
  config/packages/security.yaml
  templates/login.html.twig
  tests/Integration/Infrastructure/Controller/LoginControllerTest.php
Labels: TYPE - Tech, REVIEW-1

#248 Fix list not showing when clicking See all from regulation detail
  templates/regulation/detail.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
Labels: bug

#246 Add app rate limiter
  .env
  composer.json
  composer.lock
  config/packages/lock.yaml
  config/packages/rate_limiter.yaml
  config/packages/security.yaml
  src/Infrastructure/Symfony/EventSubscriber/RateLimiterSubscriber.php
  symfony.lock
  tests/Unit/Infrastructure/Symfony/EventSubscriber/RateLimiterSubscriberTest.php
  tests/bootstrap.php
Labels: TYPE - Tech, REVIEW-1
