Repository MTES-MCT/dialog, pull requests merged in 2023-02, with the labels that each got.

#119 Display summary sections as cards
  assets/styles/app.scss
  templates/regulation/_summary.html.twig
Labels: enhancement, mineur

#123 Fix display of calendar icons in date widget
  templates/common/form/dsfr_theme.html.twig
Labels: mineur

#150 Add missing cascades for RegulationCondition children
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Location.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.OverallPeriod.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.VehicleCharacteristics.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230214084610.php
Labels: tech

#142 Allow deleting regulations
  assets/controllers/form_submit_controller.js
  assets/controllers/modal_controller.js
  assets/controllers/modal_trigger_controller.js
  src/Application/Regulation/Command/DeleteRegulationCommand.php
  src/Application/Regulation/Command/DeleteRegulationCommandHandler.php
  src/Domain/Regulation/Exception/RegulationOrderRecordCannotBeDeletedException.php
  src/Domain/Regulation/Repository/RegulationOrderRepositoryInterface.php
  src/Infrastructure/Controller/Regulation/DeleteRegulationController.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRepository.php
  templates/base.html.twig
  templates/regulation/_delete_modal.html.twig
  templates/regulation/_items.html.twig
  templates/regulation/index.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/DeleteRegulationControllerTest.php
  tests/Unit/Application/Regulation/Command/DeleteRegulationCommandHandlerTest.php
  translations/messages.fr.xlf
Labels: enhancement

#157 Fix unit tests warnings
  tests/Unit/Infrastructure/Adapter/APIAdresseGeocoderTest.php
Labels: tech

#158 Comply tests PSR-4 compliant
  tests/Mock/APIAdresseMockClientTest.php
  tests/Unit/Application/Condition/Query/Location/GetLocationByRegulationConditionQueryHandlerTest.php
  tests/Unit/Application/Regulation/Command/DeleteRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/PublishRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep1CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep1CommandTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep2CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep2CommandTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep3CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep3CommandTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep4CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep4CommandTest.php
  tests/Unit/Domain/Condition/ConditionSetTest.php
  tests/Unit/Domain/Condition/LocationTest.php
  tests/Unit/Domain/Condition/Period/DayWeekMonthTest.php
  tests/Unit/Domain/Condition/Period/OverallPeriodTest.php
  tests/Unit/Domain/Condition/Period/PeriodTest.php
  tests/Unit/Domain/Condition/Period/SpecialDayTest.php
  tests/Unit/Domain/Condition/Period/TimePeriodOfDayTest.php
  tests/Unit/Domain/Condition/RegulationConditionTest.php
  tests/Unit/Domain/Condition/VehicleCharacteristicsTest.php
  tests/Unit/Domain/Geography/CoordinatesTest.php
  tests/Unit/Domain/Geography/GeometryFormatterTest.php
  tests/Unit/Domain/PaginationTest.php
  tests/Unit/Domain/Regulation/RegulationOrderRecordTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
  tests/Unit/Domain/Regulation/Specification/CanOrganizationAccessToRegulationTest.php
  tests/Unit/Domain/Regulation/Specification/CanRegulationOrderRecordBePublishedTest.php
  tests/Unit/Domain/User/OrganizationTest.php
  tests/Unit/Domain/User/UserTest.php
  tests/Unit/Infrastructure/Adapter/APIAdresseGeocoderTest.php
  translations/messages.fr.xlf
Labels: tech

#161 update deps
  composer.lock
  package-lock.json
Labels: tech

#160 Rename RegulationOrderListForDatexFormatView to RegulationOrderDatexListItemView
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/RegulationOrderDatexListItemView.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
Labels: tech, mineur

#167 Fix weight vehicle characteristic
  templates/api/regulations.xml.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
Labels: bug

#148 Address Turbo-related CSP errors on first load
  templates/base.html.twig
Labels: tech

#169 Create lea account
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230227095236.php
Labels: tech

#127 Add times to period fields
  .env
  .env.test
  config/services.yaml
  config/validator/Application/Regulation/Command/Steps/SaveRegulationStep3Command.xml
  docker/php/php.ini
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep3Command.php
  src/Application/Regulation/Command/Steps/SaveRegulationStep3CommandHandler.php
  src/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandler.php
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Application/Regulation/View/PeriodView.php
  src/Domain/Condition/Period/OverallPeriod.php
  src/Infrastructure/Form/Regulation/Steps/Step3FormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OverallPeriodFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Condition.Period.OverallPeriod.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230221133525.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Twig/AppExtension.php
  src/Infrastructure/Validator/SaveRegulationStep3CommandConstraint.php
  src/Infrastructure/Validator/SaveRegulationStep3CommandConstraintValidator.php
  src/Kernel.php
  templates/api/regulations.xml.twig
  templates/regulation/_items.html.twig
  templates/regulation/_summary.html.twig
  templates/regulation/steps/step3.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Steps/Step3ControllerTest.php
  tests/TimezoneHelper.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep3CommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Steps/SaveRegulationStep3CommandTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
  tests/Unit/Domain/Condition/Period/OverallPeriodTest.php
  tests/Unit/Infrastructure/Symfony/DependencyInjectionTest.php
  tests/Unit/Infrastructure/Twig/AppExtensionTest.php
  tests/Unit/Infrastructure/Validation/SaveRegulationStep3CommandConstraintValidatorTest.php
  translations/messages.fr.xlf
  translations/validators.fr.xlf
Labels: enhancement
