Repository MTES-MCT/dialog, pull requests merged in 2023-07, with the labels that each got.

#400 Add Ariane account to Dialog and Mairie de Toulouse organizations
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230703094602.php
Labels: TYPE - Tech

#401 Add indexes to improve performances
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrderRecord.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230706154140.php
Labels: TYPE - Tech

#404 Reuse UUID requirement
  src/Infrastructure/Controller/Regulation/DeleteRegulationController.php
  src/Infrastructure/Controller/Regulation/DuplicateRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/AddLocationLinkFragmentController.php
  src/Infrastructure/Controller/Regulation/Fragments/GetGeneralInfoController.php
  src/Infrastructure/Controller/Regulation/Fragments/GetLocationController.php
  src/Infrastructure/Controller/Regulation/PublishRegulationController.php
  src/Infrastructure/Controller/Regulation/RegulationDetailController.php
  src/Infrastructure/Routing/Requirements.php
Labels: refactor

#403 Use Uuid:v7 to generate timestampable uuids
  src/Infrastructure/Adapter/IdFactory.php
Labels: TYPE - Tech

#406 add new account
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20230711144619.php
Labels: TYPE - Tech

#408 Add details about Turbo and Stimulus to ADR-003
  docs/adr/003_technical_stack.md
Labels: documentation

#407 Refactor visibility controller
  assets/controllers/condition_controller.js
  assets/controllers/disable_controller.js
  assets/controllers/visibility_controller.js
  templates/regulation/_general_info_form.html.twig
  templates/regulation/_vehicle_set_form.html.twig
Labels: refactor

#413 Create admin to manage users and organizations
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  phpunit.xml.dist
  src/Domain/User/Organization.php
  src/Domain/User/User.php
  src/Infrastructure/Controller/Admin/DashboardController.php
  src/Infrastructure/Controller/Admin/OrganizationCrudController.php
  src/Infrastructure/Controller/Admin/UserCrudController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OrganizationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/UserFixture.php
  src/Infrastructure/Security/Provider/UserProvider.php
  symfony.lock
  templates/admin/index.html.twig
  templates/common/header.html.twig
  tests/Integration/Infrastructure/Controller/AbstractWebTestCase.php
  tests/Integration/Infrastructure/Controller/Admin/DashboardControllerTest.php
  tests/Integration/Infrastructure/Controller/Admin/OrganizationCrudControllerTest.php
  tests/Integration/Infrastructure/Controller/Admin/UserCrudControllerTest.php
  tests/Integration/Infrastructure/Controller/LandingControllerTest.php
  tests/Integration/Infrastructure/Controller/LoginControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/SaveRegulationGeneralInfoControllerTest.php
  tests/Unit/Domain/User/OrganizationTest.php
  tests/Unit/Domain/User/UserTest.php
  tests/Unit/Infrastructure/Security/SymfonyUserTest.php
Labels: TYPE - Tech, REVIEW-1

#417 Add matomo
  config/packages/twig.yaml
  templates/base.html.twig
  templates/common/analytics.html.twig
Labels: TYPE - Tech

#421 Fix doc export
  templates/regulation/export.md.twig
Labels: bug

#426 Update Matomo integration
  .env
  assets/analytics.js
  assets/app.js
  assets/lib.js
  config/packages/twig.yaml
  docs/tools/README.md
  docs/tools/analytics.md
  package-lock.json
  package.json
  templates/base.html.twig
  templates/common/analytics.html.twig
  webpack.config.js
Labels: bug

#427 Fix reading of Matomo system env variable by Encore
  webpack.config.js
Labels: bug
