Repository MTES-MCT/dialog, pull requests merged in 2024-05, with the labels that each got.

#758 Add registration date
  src/Application/User/Command/ConvertAccessRequestToUserCommandHandler.php
  src/Domain/User/User.php
  src/Infrastructure/Controller/Admin/UserCrudController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/UserFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.User.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240507082013.php
  tests/Unit/Application/User/Command/ConvertAccessRequestToUserCommandHandlerTest.php
  tests/Unit/Domain/User/UserTest.php
Labels: To review

#755 Documente la convention de nommage des termes métier
  docs/adr/009_nommage_metier.md
Labels: tech, To review

#762 Rendre obligatoire la définition de début/fin d'une section
  config/validator/Application/Regulation/Command/SaveNamedStreetCommand.xml
  src/Infrastructure/Form/Regulation/NamedStreetFormType.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
  translations/validators.fr.xlf
Labels: To review

#764 Ajoute le regulation uuid à l'export CIFS
  src/Application/Regulation/Query/GetCifsIncidentsQueryHandler.php
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
Labels: To review

#765 Corrige indentation de l'export DATEX de test
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
Labels: Mineur, tech, To review

#766 Mise à jour des deps
  composer.lock
  package-lock.json
Labels: tech, To review

#770 Corrige la condition de validation du point de fin
  config/validator/Application/Regulation/Command/SaveNamedStreetCommand.xml
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
Labels: Bug

#769 Corrige la suppresion d'une localisation
  src/Application/Regulation/Command/Location/SaveNamedStreetCommand.php
  src/Application/Regulation/Command/Location/SaveNumberedRoadCommand.php
  templates/regulation/fragments/_measure_form.html.twig
Labels: To review, Bug critique

#772 Retire le cas début sans fin et inversement dans le QueryHandler
  src/Application/Regulation/Query/Location/GetNamedStreetGeometryQueryHandler.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
  tests/Unit/Application/Regulation/Query/Location/GetNamedStreetGeometryQueryHandlerTest.php
Labels: tech, To review

#771 Sections : applique une tolérance pour le calcul des morceaux de rattachement
  src/Infrastructure/Adapter/LineSectionMaker.php
  tests/Integration/Infrastructure/Adapter/LineSectionMakerTest.php
Labels: Bug, Localisations, To review

#774 Add polyline_to_geojson tool
  docs/tools/cifs.md
  tools/polyline_to_geojson.py
Labels: tech, To review

#776 Permet de limiter les arrêtés exportés en CIFS
  config/services.yaml
  docs/deployment/README.md
  src/Application/Regulation/Query/GetCifsIncidentsQueryHandler.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
Labels: To review

#783 Corrige le recalcul des géométries de type Voie nommée
  config/validator/Application/Regulation/Command/SaveNamedStreetCommand.xml
  src/Application/Regulation/Command/Location/RoadCommandInterface.php
  src/Application/Regulation/Command/Location/SaveLocationCommandHandler.php
  src/Application/Regulation/Command/Location/SaveNumberedRoadCommand.php
Labels: Bug, To review

#784 Restreint le CIFS par loc.uuid plutôt que roc.uuid
  config/services.yaml
  docs/deployment/README.md
  src/Application/Regulation/Query/GetCifsIncidentsQueryHandler.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
Labels: Bug, To review

#786 Allow to have max_input_var to 5000
  composer.json
  docker/php/php.ini
Labels: Bug, tech, To review

#773 Geocoder une voie nommee grâce aux troncons de route
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/Cifs/PolylineMaker.php
  src/Infrastructure/Persistence/Doctrine/BdTopoMigrations/Version20240515085654.php
  tests/Integration/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
  tests/Integration/Infrastructure/Cifs/PolylineMakerTest.php
  tools/bdtopo_update
  tools/bdtopo_update.config.json
Labels: To review

#787 Améliore accessibilité des champs avec autocomplétion
  assets/controllers/_stimulus_autocomplete.js
  assets/controllers/autocomplete_controller.js
  assets/styles/components/autocomplete.scss
  package-lock.json
  package.json
  templates/location/named_street/_from_point.html.twig
  templates/location/named_street/_to_point.html.twig
  templates/regulation/fragments/_city_completions.html.twig
  templates/regulation/fragments/_intersection_completions.html.twig
  templates/regulation/fragments/_measure_form.html.twig
  templates/regulation/fragments/_road_name_completions.html.twig
  templates/regulation/fragments/_road_numbers_completions.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetAddressCompletionFragmentControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetCityCompletionFragmentControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetDepartmentalRoadCompletionFragmentControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetIntersectionCompletionFragmentControllerTest.php
  translations/messages.fr.xlf
Labels: UI / UX, To review

#788 Ne remonte dans l'export CIFS que les arretés en cours de validité
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MeasureFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderRecordFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Integration/Infrastructure/Controller/StatisticsControllerTest.php
Labels: To review

#794 Expose le champ source dans le DATEX
  docs/spec/datex2/DATEXII_3_DiaLogExtension.xsd
  docs/spec/datex2/DATEXII_3_LocationReferencing.xsd
  docs/spec/datex2/DATEXII_3_TrafficRegulation.xsd
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/RegulationOrderDatexListItemView.php
  templates/api/regulations.xml.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
Labels: To review

#782 Ajoute des liens d'évitement (skiplinks)
  templates/accessibility_statement.html.twig
  templates/common/skiplinks.html.twig
  templates/ecodesign_statement.html.twig
  templates/layouts/_base.html.twig
  templates/layouts/public.html.twig
  templates/legal.html.twig
  templates/regulation/create.html.twig
  templates/regulation/detail.html.twig
  tests/Integration/Infrastructure/Controller/AbstractWebTestCase.php
  tests/Integration/Infrastructure/Controller/LandingControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  translations/messages.fr.xlf
Labels: UI / UX, To review

#797 Expose l'UUID localisation dans la page de détail arrêté
  src/Application/Regulation/View/Measure/LocationView.php
  src/Application/Regulation/View/Measure/MeasureView.php
  templates/regulation/fragments/_measure.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetMeasureControllerTest.php
  tests/Unit/Application/Regulation/Query/Measure/GetMeasuresQueryHandlerTest.php
Labels: To review
