Repository MTES-MCT/dialog, pull requests merged in 2024-03, with the labels that each got.

#670 Corrige erreur SSH known_hosts lors de l'import Eudonet
  .github/workflows/eudonet_paris_import.yml
Labels: Bug, tech, To review

#665 Déplace le géocodage des intersections Eudonet vers SaveLocationCommandHandler
  src/Application/EudonetParis/Command/ImportEudonetParisRegulationCommandHandler.php
  src/Application/Regulation/Command/Location/SaveLocationCommand.php
  src/Application/Regulation/Command/Location/SaveLocationCommandHandler.php
  src/Infrastructure/EudonetParis/EudonetParisTransformer.php
  tests/Unit/Application/Regulation/Command/Location/SaveLocationCommandHandlerTest.php
  tests/Unit/Infrastructure/EudonetParis/EudonetParisTransformerTest.php
Labels: tech, To review

#668 Fix geocoder special characters
  src/Infrastructure/Adapter/IgnWfsRoadGeocoder.php
  tests/Mock/IgnWfsMockClient.php
  tests/Unit/Infrastructure/Adapter/IgnWfsRoadGeocoderTest.php
Labels: Bug, To review

#672 Allow permanent regulation order to have no end date
  config/validator/Application/Regulation/Command/SavePeriodCommand.xml
  src/Application/Regulation/Command/Period/SavePeriodCommand.php
  src/Application/Regulation/Command/Period/SavePeriodCommandHandler.php
  src/Domain/Condition/Period/Period.php
  src/Domain/Regulation/RegulationOrder.php
  src/Infrastructure/Controller/Regulation/Fragments/AddMeasureController.php
  src/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureController.php
  src/Infrastructure/Form/Regulation/Measure/MeasureFormType.php
  src/Infrastructure/Form/Regulation/PeriodFormType.php
  templates/regulation/_period.html.twig
  templates/regulation/fragments/_measure_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  tests/Unit/Application/Regulation/Command/Period/SavePeriodCommandHandlerTest.php
  tests/Unit/Domain/Condition/Period/PeriodTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
Labels: To review

#674 Gère les erreurs des réponses du géocodeur IGN
  src/Infrastructure/Adapter/IgnWfsRoadGeocoder.php
  tests/Unit/Infrastructure/Adapter/IgnWfsRoadGeocoderTest.php
Labels: Bug, To review

#675 [admin] Fix user duplication
  src/Infrastructure/Controller/Admin/UserCrudController.php
Labels: To review

#680 Fix error handling in Eudonet Addok bundle download script
  .github/workflows/eudonet_paris_import.yml
  tools/download_addok_bundle.sh
Labels: To review

#682 Eudonet: fix missing -o in script
  tools/download_addok_bundle.sh
Labels: Bug

#657 Réutilise les coordonnées d'adresses de début/fin d'Eudonet Paris
  src/Application/Regulation/Command/Location/SaveLocationCommand.php
  src/Application/Regulation/Command/Location/SaveLocationCommandHandler.php
  src/Infrastructure/EudonetParis/EudonetParisExtractor.php
  src/Infrastructure/EudonetParis/EudonetParisTransformer.php
  tests/Mock/EudonetParis/EudonetParisMockHttpClient.php
  tests/Mock/EudonetParis/eudonet_paris.3400.mock.json
  tests/Unit/Application/Regulation/Command/Location/SaveLocationCommandHandlerTest.php
  tests/Unit/Infrastructure/EudonetParis/EudonetParisExtractorTest.php
  tests/Unit/Infrastructure/EudonetParis/EudonetParisTransformerTest.php
Labels: Localisations, To review

#685 Corrige la déclaration de système de coordonnées de Location.geometry
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Location.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240318161612.php
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
Labels: Bug, tech

#677 Remplace l'API WFS IGN par la BD TOPO
  .env
  .github/workflows/bdtopo_migrate.yml
  .github/workflows/ci.yml
  .github/workflows/eudonet_paris_import.yml
  Makefile
  README.md
  config/packages/bdtopo/doctrine_migrations.yaml
  config/packages/doctrine.yaml
  config/packages/framework.yaml
  config/services.yaml
  docker-compose.yml
  docs/adr/008_bdtopo.md
  docs/deployment/README.md
  docs/tools/bdtopo.md
  docs/tools/data.md
  phpunit.xml.dist
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/Adapter/RoadGeocoder.php
  src/Infrastructure/Persistence/Doctrine/BdTopoMigrations/Version20240320122522.php
  src/Infrastructure/Persistence/Doctrine/BdTopoMigrations/Version20240320130731.php
  tests/Mock/BdTopoRoadGeocoderMock.php
  tests/Mock/IgnWfsMockClient.php
  tests/Mock/IgnWfsMockClientTest.php
  tests/Unit/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
  tests/Unit/Infrastructure/Adapter/RoadGeocoderTest.php
  tools/bdtopo_update
  tools/bdtopo_update.config.json
  tools/scalingodbtunnel
Labels: To review

#692 Fix bdtopo_migrate CI
  .github/workflows/bdtopo_migrate.yml
  Makefile
Labels: To review

#669 Calcule la section entre 2 numéros d'une voie nommée
  src/Application/LaneSectionMakerInterface.php
  src/Application/LineSectionMakerInterface.php
  src/Application/Regulation/Command/Location/SaveLocationCommandHandler.php
  src/Domain/Geography/Coordinates.php
  src/Domain/Geography/GeoJSON.php
  src/Domain/Regulation/Repository/LocationRepositoryInterface.php
  src/Infrastructure/Adapter/LaneSectionMaker.php
  src/Infrastructure/Adapter/LineSectionMaker.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Mock/APIAdresseMockClient.php
  tests/Mock/BdTopoRoadGeocoderMock.php
  tests/Unit/Application/Regulation/Command/Location/SaveLocationCommandHandlerTest.php
  tests/Unit/Domain/Geography/GeoJSONTest.php
  tests/Unit/Infrastructure/Adapter/LaneSectionMakerTest.php
  tests/Unit/Infrastructure/Adapter/LineSectionMakerTest.php
Labels: To review

#703 Corrige la duplication d'arrete permanent
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
Labels: To review
