Repository MTES-MCT/dialog, pull requests merged in 2024-01, with the labels that each got.

#578 LocationNew model
  docs/adr/002_mcd.md
  src/Application/Regulation/Command/SaveRegulationLocationCommandHandler.php
  src/Domain/Regulation/LocationNew.php
  src/Domain/Regulation/Measure.php
  src/Domain/Regulation/Repository/LocationNewRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.LocationNew.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Measure.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20231218150925.php
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20231218154722.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationNewRepository.php
  tests/Unit/Application/Regulation/Command/SaveRegulationLocationCommandHandlerTest.php
  tests/Unit/Domain/Regulation/LocationNewTest.php
  tests/Unit/Domain/Regulation/MeasureTest.php
Labels: TYPE - Tech

#595 IGN WFS: Ignore accents in nom_minuscule
  src/Infrastructure/Adapter/IgnWfsRoadGeocoder.php
  tests/Mock/IgnWfsMockClient.php
  tests/Unit/Infrastructure/Adapter/IgnWfsRoadGeocoderTest.php
Labels: Bug, REVIEW-1

#613 Split GetRegulationOrderRecordSummaryQueryHandler
  src/Application/Regulation/Query/GetGeneralInfoQuery.php
  src/Application/Regulation/Query/GetGeneralInfoQueryHandler.php
  src/Application/Regulation/Query/GetRegulationOrderRecordSummaryQueryHandler.php
  src/Application/Regulation/Query/Location/GetRegulationLocationsQuery.php
  src/Application/Regulation/Query/Location/GetRegulationLocationsQueryHandler.php
  src/Application/Regulation/View/GeneralInfoView.php
  src/Application/Regulation/View/RegulationOrderLocationsView.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Controller/Regulation/ExportRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/AddLocationController.php
  src/Infrastructure/Controller/Regulation/Fragments/GetGeneralInfoController.php
  src/Infrastructure/Controller/Regulation/Fragments/GetLocationController.php
  src/Infrastructure/Controller/Regulation/RegulationDetailController.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/_overall_period.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/export.md.twig
  templates/regulation/fragments/_general_info.html.twig
  templates/regulation/fragments/_location.added.stream.html.twig
  templates/regulation/fragments/_location.html.twig
  templates/regulation/fragments/_location_delete_form.html.twig
  templates/regulation/fragments/_publication_button.html.twig
  tests/Unit/Application/Regulation/Query/GetGeneralInfoQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/Location/GetLocationByUuidQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/Location/GetRegulationLocationsQueryHandlerTest.php
  tests/Unit/Application/Regulation/View/GeneralInfoViewTest.php
Labels: To review

#600 Refactor: move all locationNew logic
  src/Application/Regulation/Command/Location/DeleteLocationNewCommand.php
  src/Application/Regulation/Command/Location/DeleteLocationNewCommandHandler.php
  src/Application/Regulation/Command/Location/SaveLocationNewCommand.php
  src/Application/Regulation/Command/Location/SaveLocationNewCommandHandler.php
  src/Application/Regulation/Command/SaveMeasureCommand.php
  src/Application/Regulation/Command/SaveMeasureCommandHandler.php
  src/Application/Regulation/Command/SaveRegulationLocationCommand.php
  src/Application/Regulation/Command/SaveRegulationLocationCommandHandler.php
  src/Domain/Regulation/Measure.php
  src/Domain/Regulation/Repository/LocationNewRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.LocationNew.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Measure.orm.xml
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationNewRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Unit/Application/Regulation/Command/Location/DeleteLocationNewCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Location/SaveLocationNewCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveMeasureCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveRegulationLocationCommandHandlerTest.php
  tests/Unit/Domain/Regulation/LocationNewTest.php
  tests/Unit/Domain/Regulation/MeasureTest.php
  tests/Unit/Infrastructure/Repository/LocationNewRepositoryTest.php
Labels: To review

#620 Add FeatureFlagService
  config/services.yaml
  src/Infrastructure/FeatureFlagService.php
  src/Infrastructure/Twig/AppExtension.php
  tests/Unit/Infrastructure/FeatureFlagServiceTest.php
  tests/Unit/Infrastructure/Twig/AppExtensionTest.php
Labels: tech, To review
