Repository MTES-MCT/dialog, pull requests merged in 2024-07, with the labels that each got.

#847 Intègre les données zones JOP
  .env
  config/packages/monolog.yaml
  config/services.yaml
  data/jop/README.md
  data/jop/zones.geojson
  docs/deployment/README.md
  src/Application/JOP/Command/ImportJOPRegulationCommand.php
  src/Application/JOP/Command/ImportJOPRegulationCommandHandler.php
  src/Application/Regulation/Command/SaveMeasureCommand.php
  src/Application/RoadGeocoderInterface.php
  src/Domain/Regulation/Enum/RegulationOrderRecordSourceEnum.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/JOP/JOPExecutor.php
  src/Infrastructure/JOP/JOPExtractor.php
  src/Infrastructure/JOP/JOPTransformer.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Symfony/Command/JOPImportCommand.php
  tests/Unit/Application/JOP/Command/ImportJOPRegulationCommandHandlerTest.php
  tests/Unit/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
  tests/Unit/Infrastructure/JOP/JOPExecutorTest.php
  tests/Unit/Infrastructure/JOP/JOPExtractorTest.php
  tests/Unit/Infrastructure/JOP/JOPTransformerTest.php
  tests/Unit/Infrastructure/Symfony/Command/JOPImportCommandTest.php
  tools/jop_prepare.sh
  tools/shp2geojson.py
  translations/messages.fr.xlf
Labels: To review

#841 Proposer un mode lecture seule (ouverture au public) pour la page qui liste les arrêtés
  config/packages/security.yaml
  src/Application/Regulation/Query/GetRegulationsQuery.php
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Application/Regulation/View/RegulationOrderListItemView.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Controller/Regulation/ListRegulationsController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/common/header.html.twig
  templates/regulation/_items.html.twig
  templates/regulation/index.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
Labels: To review

#837 Include Eudonet measures with no specific dates
  src/Infrastructure/EudonetParis/EudonetParisExtractor.php
  src/Infrastructure/EudonetParis/EudonetParisTransformer.php
  tests/Integration/Infrastructure/Symfony/Command/EudonetParis/EudonetParisImportCommandTest.php
  tests/Mock/EudonetParis/eudonet_paris.1200.mock.json
  tests/Unit/Infrastructure/EudonetParis/EudonetParisExtractorTest.php
  tests/Unit/Infrastructure/EudonetParis/EudonetParisTransformerTest.php
Labels: Impact : GPS, To review

#864 Restreint l'accès aux brouillons aux utilisateurs connectés
  src/Domain/Regulation/Specification/CanViewRegulationDetail.php
  src/Infrastructure/Controller/Regulation/RegulationDetailController.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Unit/Domain/Regulation/Specification/CanViewRegulationDetailTest.php
Labels: Bug

#862 Limite la précision des coordonnées carto à 5 décimales
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  tests/Integration/Infrastructure/Controller/Map/MapControllerTest.php
Labels: tech, To review

#854 Carte "responsive" (amélioration de la hauteur - et de la largeur - de la carte)
  assets/customElements/map.js
  assets/styles/map.scss
  assets/styles/utilities/dsfr-extensions/sizing.css
  templates/map/map.html.twig
Labels: To review

#863 Ajuste la tolérance d'affichage des géométries
  assets/customElements/map.js
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  tests/Integration/Infrastructure/Controller/Map/MapControllerTest.php
  tests/Integration/Infrastructure/Symfony/Command/EudonetParis/EudonetParisImportCommandTest.php
Labels: tech, To review

#868 Ajout de page mot de passe oublié
  src/Infrastructure/Controller/Security/ForgotPasswordController.php
  templates/forgot-password.html.twig
  templates/login.html.twig
  tests/Integration/Infrastructure/Controller/Security/ForgotPasswordControllerTest.php
  tests/Integration/Infrastructure/Controller/Security/LoginControllerTest.php
  translations/messages.fr.xlf
Labels: UI / UX, To review

#878 Update deps
  composer.lock
  package-lock.json
Labels: tech

#872 Gestion des rôles utilisateurs (partie 1)
  .env
  config/packages/security.yaml
  config/services.yaml
  docs/deployment/README.md
  docs/tools/admin.md
  src/Application/User/Command/ConvertAccessRequestToUserCommandHandler.php
  src/Domain/Regulation/Specification/CanUseRawGeoJSON.php
  src/Domain/User/Enum/OrganizationRolesEnum.php
  src/Domain/User/Enum/UserRolesEnum.php
  src/Domain/User/Organization.php
  src/Domain/User/OrganizationUser.php
  src/Domain/User/Repository/OrganizationUserRepositoryInterface.php
  src/Domain/User/User.php
  src/Infrastructure/Controller/Admin/UserCrudController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OrganizationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/UserFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Organization.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/User.OrganizationUser.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/User.User.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240709115447.php
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240709154626.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/OrganizationUserRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/UserRepository.php
  src/Infrastructure/Security/Provider/UserProvider.php
  templates/common/header.html.twig
  tests/Integration/Infrastructure/Controller/AbstractWebTestCase.php
  tests/Integration/Infrastructure/Controller/StatisticsControllerTest.php
  tests/Unit/Application/User/Command/ConvertAccessRequestToUserCommandHandlerTest.php
  tests/Unit/Domain/User/OrganizationTest.php
  tests/Unit/Domain/User/OrganizationUserTest.php
  tests/Unit/Domain/User/UserTest.php
  tests/Unit/Infrastructure/Security/SymfonyUserTest.php
Labels: tech, To review

#879 Gestion des rôles utilisateurs (partie 2)
  config/validator/Domain/User/OrganizationUser.xml
  src/Domain/User/User.php
  src/Infrastructure/Controller/Admin/DashboardController.php
  src/Infrastructure/Controller/Admin/OrganizationUserCrudController.php
  tests/Integration/Infrastructure/Controller/Admin/OrganizationUserCrudControllerTest.php
  tests/Unit/Domain/User/UserTest.php
Labels: To review

#880 Gestion des rôles (partie 3)
  config/packages/security.yaml
  src/Application/User/View/UserOrganizationView.php
  src/Infrastructure/Controller/Organization/ListOrganizationsController.php
  src/Infrastructure/Controller/Regulation/AddRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/SaveGeneralInfoController.php
  src/Infrastructure/Form/Regulation/GeneralInfoFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OrganizationFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/OrganizationUserRepository.php
  src/Infrastructure/Security/Provider/UserProvider.php
  src/Infrastructure/Security/SymfonyUser.php
  templates/organization/index.html.twig
  tests/Integration/Infrastructure/Controller/AbstractWebTestCase.php
  tests/Integration/Infrastructure/Controller/Organization/ListOrganizationsControllerTest.php
  tests/Unit/Infrastructure/Security/SymfonyUserTest.php
  translations/messages.fr.xlf
Labels: To review

#883 Gestion des rôles utilisateurs (partie 4)
  src/Application/User/Query/GetOrganizationUsersQuery.php
  src/Application/User/Query/GetOrganizationUsersQueryHandler.php
  src/Application/User/View/OrganizationView.php
  src/Application/User/View/UserView.php
  src/Domain/User/Repository/OrganizationUserRepositoryInterface.php
  src/Infrastructure/Controller/Organization/ListOrganizationsController.php
  src/Infrastructure/Controller/Organization/User/ListUsersController.php
  src/Infrastructure/Form/Regulation/GeneralInfoFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/OrganizationUserRepository.php
  src/Infrastructure/Security/SymfonyUser.php
  src/Infrastructure/Security/Voter/OrganizationVoter.php
  templates/organization/index.html.twig
  templates/user/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/ListOrganizationsControllerTest.php
  tests/Integration/Infrastructure/Controller/Organization/User/ListUsersControllerTest.php
  tests/Unit/Application/User/Query/GetOrganizationUsersQueryHandlerTest.php
  tests/Unit/Infrastructure/Security/SymfonyUserTest.php
  translations/messages.fr.xlf
Labels: To review

#886 Gestion des rôles utilisateurs (partie 5)
  config/validator/Application/User/SaveUserOrganizationCommand.xml
  src/Application/User/Command/SaveUserOrganizationCommand.php
  src/Application/User/Command/SaveUserOrganizationCommandHandler.php
  src/Application/User/Query/GetOrganizationUserQuery.php
  src/Application/User/Query/GetOrganizationUserQueryHandler.php
  src/Domain/User/Exception/UserOrganizationNotFoundException.php
  src/Domain/User/Repository/OrganizationUserRepositoryInterface.php
  src/Infrastructure/Controller/Organization/AbstractOrganizationController.php
  src/Infrastructure/Controller/Organization/User/EditUserController.php
  src/Infrastructure/Controller/Organization/User/ListUsersController.php
  src/Infrastructure/Form/User/RolesFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/OrganizationUserRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/UserRepository.php
  src/Infrastructure/Security/Voter/OrganizationVoter.php
  templates/user/edit.html.twig
  templates/user/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/User/EditUserControllerTest.php
  tests/Integration/Infrastructure/Controller/Organization/User/ListUsersControllerTest.php
  tests/Unit/Application/User/Command/SaveUserOrganizationCommandHandlerTest.php
  tests/Unit/Application/User/Query/GetOrganizationUserQueryHandlerTest.php
  tests/Unit/Application/User/Query/GetOrganizationUsersQueryHandlerTest.php
Labels: To review

#889 Uniquement l'administrateur de l'orga peut gérer les comptes utilisateurs
  src/Infrastructure/Controller/Organization/User/EditUserController.php
  src/Infrastructure/Controller/Organization/User/ListUsersController.php
  src/Infrastructure/Security/Voter/OrganizationVoter.php
  templates/organization/user/edit.html.twig
  templates/organization/user/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/User/ListUsersControllerTest.php
Labels: Bug, To review

#892 Fix scalingo post-deployment scripts
  Makefile
  Procfile
Labels: To review

#894 Mise à jour du DSFR en version 1.12.1
  composer.lock
  package-lock.json
  package.json
  templates/common/footer.html.twig
Labels: tech, To review
