Repository MTES-MCT/dialog, pull requests merged in 2024-08, with the labels that each got.

#895 Design de la liste des organisations
  public/images/city-hall.png
  templates/organization/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/ListOrganizationsControllerTest.php
  translations/messages.fr.xlf
Labels: UI / UX, To review

#904 Fix CI
  tests/Integration/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
Labels: Bug, To review

#903 Ajout du menu latéral
  templates/organization/_menu.html.twig
  templates/organization/user/edit.html.twig
  templates/organization/user/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/User/ListUsersControllerTest.php
  translations/messages.fr.xlf
Labels: UI / UX, To review

#905 Supprime un utilisateur d'une organisation
  assets/styles/components/regulation/table.scss
  src/Application/User/Command/DeleteOrganizationUserCommand.php
  src/Application/User/Command/DeleteOrganizationUserCommandHandler.php
  src/Application/User/View/UserOrganizationView.php
  src/Domain/User/Repository/OrganizationUserRepositoryInterface.php
  src/Domain/User/Repository/UserRepositoryInterface.php
  src/Infrastructure/Controller/Organization/User/DeleteOrganizationUserController.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/OrganizationUserRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/UserRepository.php
  templates/organization/user/index.html.twig
  templates/regulation/_items.html.twig
  tests/Integration/Infrastructure/Controller/Organization/User/DeleteOrganizationUserControllerTest.php
  tests/Unit/Application/User/Command/DeleteOrganizationUserCommandHandlerTest.php
  translations/messages.fr.xlf
Labels: To review

#906 Ajoute une documentation sur l'intégration JOP
  docs/tools/jop.md
Labels: To review

#907 Edition d'un utilisateur
  config/validator/Application/User/SaveUserOrganizationCommand.xml
  src/Application/User/Command/SaveUserOrganizationCommand.php
  src/Application/User/Command/SaveUserOrganizationCommandHandler.php
  src/Domain/User/Exception/EmailAlreadyExistsException.php
  src/Domain/User/Repository/OrganizationUserRepositoryInterface.php
  src/Domain/User/Repository/UserRepositoryInterface.php
  src/Domain/User/Specification/IsEmailAlreadyExists.php
  src/Domain/User/Specification/IsUserAlreadyRegisteredInOrganization.php
  src/Infrastructure/Controller/Organization/User/EditUserController.php
  src/Infrastructure/Form/User/UserFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/OrganizationUserRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/UserRepository.php
  templates/organization/user/edit.html.twig
  tests/Integration/Infrastructure/Controller/Organization/User/EditUserControllerTest.php
  tests/Unit/Application/User/Command/SaveUserOrganizationCommandHandlerTest.php
  tests/Unit/Domain/User/Specification/IsAccessAlreadyRequestedTest.php
  tests/Unit/Domain/User/Specification/IsEmailAlreadyExistsTest.php
  tests/Unit/Domain/User/Specification/IsUserAlreadyRegisteredInOrganizationTest.php
  translations/messages.fr.xlf
  translations/validators.fr.xlf
Labels: To review

#911 Update to Symfony 6.4.10
  composer.lock
  package-lock.json
  src/Domain/User/User.php
  src/Infrastructure/Adapter/APIAdresseGeocoder.php
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/Adapter/LaneSectionMaker.php
  src/Infrastructure/Adapter/LineSectionMaker.php
  src/Infrastructure/BacIdf/BacIdfTransformer.php
  src/Infrastructure/Controller/Regulation/ExportRegulationController.php
  src/Infrastructure/EudonetParis/EudonetParisClient.php
  src/Infrastructure/EudonetParis/EudonetParisExtractor.php
  src/Infrastructure/EudonetParis/EudonetParisTransformer.php
  src/Infrastructure/Form/Regulation/DailyRangeFormType.php
  src/Infrastructure/Form/Regulation/GeneralInfoFormType.php
  src/Infrastructure/Form/Regulation/LocationFormType.php
  src/Infrastructure/Form/Regulation/Measure/MeasureFormType.php
  src/Infrastructure/Form/Regulation/NamedStreetFormType.php
  src/Infrastructure/Form/Regulation/NumberedRoadFormType.php
  src/Infrastructure/Form/Regulation/PeriodFormType.php
  src/Infrastructure/Form/Regulation/VehicleSetFormType.php
  src/Infrastructure/JOP/JOPExecutor.php
  src/Infrastructure/JOP/JOPTransformer.php
  src/Infrastructure/Persistence/Doctrine/DBAL/Types/GeoJSONGeometryType.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/OrganizationUserRepository.php
  src/Infrastructure/Security/Provider/UserProvider.php
  src/Infrastructure/Symfony/Command/LoadFrCityDataCommand.php
  src/Infrastructure/Symfony/DependencyInjection/CifsFilterSetEnvVarProcessor.php
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/DeleteMeasureFragmentControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/SaveRegulationGeneralInfoControllerTest.php
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
Labels: tech, To review

#912 Rename UserOrganization to OrganizationUser
  config/validator/Application/User/SaveOrganizationUserCommand.xml
  src/Application/Regulation/Command/DeleteRegulationCommand.php
  src/Application/Regulation/Command/DeleteRegulationCommandHandler.php
  src/Application/User/Command/DeleteOrganizationUserCommandHandler.php
  src/Application/User/Command/SaveOrganizationUserCommand.php
  src/Application/User/Command/SaveOrganizationUserCommandHandler.php
  src/Application/User/Query/GetOrganizationUserQueryHandler.php
  src/Domain/Regulation/Specification/CanOrganizationAccessToRegulation.php
  src/Domain/User/Exception/OrganizationUserNotFoundException.php
  src/Domain/User/Repository/OrganizationUserRepositoryInterface.php
  src/Infrastructure/Controller/Organization/ListOrganizationsController.php
  src/Infrastructure/Controller/Organization/User/AddUserController.php
  src/Infrastructure/Controller/Organization/User/DeleteOrganizationUserController.php
  src/Infrastructure/Controller/Organization/User/EditUserController.php
  src/Infrastructure/Controller/Regulation/AddRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/SaveGeneralInfoController.php
  src/Infrastructure/Controller/Regulation/ListRegulationsController.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/OrganizationUserRepository.php
  src/Infrastructure/Security/Provider/UserProvider.php
  src/Infrastructure/Security/SymfonyUser.php
  src/Infrastructure/Security/Voter/OrganizationVoter.php
  templates/regulation/_items.html.twig
  tests/Integration/Infrastructure/Controller/AbstractWebTestCase.php
  tests/Unit/Application/User/Command/SaveOrganizationUserCommandHandlerTest.php
  tests/Unit/Application/User/Query/GetOrganizationUserQueryHandlerTest.php
  tests/Unit/Domain/Regulation/Specification/CanOrganizationAccessToRegulationTest.php
  tests/Unit/Infrastructure/Security/SymfonyUserTest.php
Labels: tech, To review

#913 Ajout du breadcrumb
  templates/common/breadcrumb.html.twig
  templates/organization/index.html.twig
  templates/organization/user/form.html.twig
  templates/organization/user/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/ListOrganizationsControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#910 Autoriser la publication uniquement aux rôles admin et publisher
  src/Domain/User/Specification/CanUserPublishRegulation.php
  src/Infrastructure/Controller/Regulation/Fragments/AddMeasureController.php
  src/Infrastructure/Controller/Regulation/PublishRegulationController.php
  src/Infrastructure/Controller/Regulation/RegulationDetailController.php
  src/Infrastructure/Security/Voter/RegulationOrderRecordVoter.php
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_measure.added.stream.html.twig
  templates/regulation/fragments/_publication_button.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/PublishRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Unit/Domain/User/Specification/CanUserPublishRegulationTest.php
Labels: To review

#916 Simplification de l'affichage des arrếtés
  src/Application/Regulation/Query/GetRegulationsQuery.php
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Controller/Regulation/DeleteRegulationController.php
  src/Infrastructure/Controller/Regulation/ListRegulationsController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/_items.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/index.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/DeleteRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
Labels: To review

#919 Retire contrainte de longueur sur RawGeoJSON.label
  config/validator/Application/Regulation/Command/SaveRawGeoJSONCommand.xml
  src/Infrastructure/JOP/JOPTransformer.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Location.RawGeoJSON.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240820083209.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  tests/Unit/Infrastructure/JOP/JOPTransformerTest.php
Labels: To review

#874 Ajoute intégration Litteralis / MEL
  .env
  .env.test
  assets/customElements/map.js
  config/packages/framework.yaml
  config/packages/monolog.yaml
  config/services.yaml
  docs/adr/007_eudonet_paris_integration.md
  docs/adr/010_litteralis.md
  docs/adr/010_litteralis_lineaire.png
  docs/adr/010_litteralis_polygone.png
  docs/tools/litteralis.md
  src/Application/Litteralis/Command/CleanUpLitteralisRegulationsBeforeImportCommand.php
  src/Application/Litteralis/Command/CleanUpLitteralisRegulationsBeforeImportCommandHandler.php
  src/Application/Litteralis/Command/ImportLitteralisRegulationCommand.php
  src/Application/Litteralis/Command/ImportLitteralisRegulationCommandHandler.php
  src/Application/RoadGeocoderInterface.php
  src/Domain/Regulation/Enum/RegulationOrderRecordSourceEnum.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/Litteralis/LitteralisClient.php
  src/Infrastructure/Litteralis/LitteralisExecutor.php
  src/Infrastructure/Litteralis/LitteralisExtractor.php
  src/Infrastructure/Litteralis/LitteralisPeriodParser.php
  src/Infrastructure/Litteralis/LitteralisReportFormatter.php
  src/Infrastructure/Litteralis/LitteralisReporter.php
  src/Infrastructure/Litteralis/LitteralisReporterFactory.php
  src/Infrastructure/Litteralis/LitteralisTransformer.php
  src/Infrastructure/MEL/MELExecutor.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Symfony/Command/MELImportCommand.php
  src/Infrastructure/Symfony/Command/MELRegulationGetCommand.php
  src/Infrastructure/Twig/AppExtension.php
  tests/Integration/Infrastructure/Litteralis/LitteralisReportFormatterTest.php
  tests/Integration/Infrastructure/Symfony/Command/MELImportCommandTest.php
  tests/Integration/Infrastructure/Symfony/Command/MELRegulationGetCommandTest.php
  tests/Mock/Litteralis/LitteralisMockHttpClient.data.json
  tests/Mock/Litteralis/LitteralisMockHttpClient.php
  tests/Unit/Application/Litteralis/Command/CleanUpLitteralisRegulationsBeforeImportCommandHandlerTest.php
  tests/Unit/Application/Litteralis/Command/ImportLitteralisRegulationCommandHandlerTest.php
  tests/Unit/Application/Litteralis/Command/ImportLitteralisRegulationCommandTest.php
  tests/Unit/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisClientTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExecutorTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExtractorTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisPeriodParserTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisReporterFactoryTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisReporterTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisTransformerTest.data.json
  tests/Unit/Infrastructure/Litteralis/LitteralisTransformerTest.php
  tests/Unit/Infrastructure/Symfony/Command/MELImportCommandTest.php
  translations/messages.fr.xlf
Labels: To review

#925 Intègre la zone rouge cérémonie d'ouverture paralympiques
  .env
  config/services.yaml
  data/jop/README.md
  data/jop/files/para_ouverture.geojson
  data/jop/files/zones.geojson
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/JOP/JOPExtractor.php
  src/Infrastructure/JOP/JOPTransformer.php
  tests/Unit/Infrastructure/JOP/JOPExtractorTest.php
  tests/Unit/Infrastructure/JOP/JOPTransformerTest.php
Labels: To review

#921 Ajoute l'URL publique de l'arrêté dans le DATEX
  docs/spec/datex2/DATEXII_3_DiaLogExtension.xsd
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/RegulationOrderDatexListItemView.php
  templates/api/regulations.xml.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
Labels: To review

#931 Corrige affichage de l'entête de la liste
  assets/styles/components/regulation/index.scss
  assets/styles/components/regulation/table.scss
  assets/styles/utilities/index.scss
  assets/styles/utilities/text.css
  templates/regulation/_items.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/DeleteRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
Labels: Bug, UI / UX, To review

#932 Associe l'identifiant arrêté à toutes les erreurs Litteralis
  src/Infrastructure/Litteralis/LitteralisReportFormatter.php
  src/Infrastructure/Litteralis/LitteralisTransformer.php
  tests/Integration/Infrastructure/Litteralis/LitteralisReportFormatterTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisTransformerTest.php
Labels: To review

#933 RegulationOrderRecordStatusEnum devient un vrai enum
  src/Application/Regulation/Command/PublishRegulationCommandHandler.php
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommandHandler.php
  src/Application/Regulation/View/GeneralInfoView.php
  src/Domain/Regulation/Enum/RegulationOrderRecordStatusEnum.php
  src/Domain/Regulation/RegulationOrderRecord.php
  src/Domain/Regulation/Specification/CanViewRegulationDetail.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderRecordFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/create.html.twig
  tests/Unit/Application/Regulation/Command/SaveRegulationGeneralInfoCommandHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetGeneralInfoQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
  tests/Unit/Application/Regulation/View/GeneralInfoViewTest.php
  tests/Unit/Domain/Regulation/RegulationOrderRecordTest.php
  tests/Unit/Domain/Regulation/Specification/CanViewRegulationDetailTest.php
Labels: tech, To review
