Repository MTES-MCT/dialog, pull requests merged in 2024-04, with the labels that each got.

#709 Refactor: utilise les entités dans la requête SQL DATEX
  config/packages/jsor_doctrine_postgis.yaml
  phpunit.xml.dist
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/DatexTrafficRegulationView.php
  src/Infrastructure/Persistence/Doctrine/DBAL/Types/GeoJSONGeometryType.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Location.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240403144652.php
  src/Infrastructure/Persistence/Doctrine/PostGIS/Event/ORMSchemaEventSubscriber.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/api/regulations.xml.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
Labels: To review

#702 Add periods to DATEX export
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/DatexTrafficRegulationView.php
  src/Application/Regulation/View/DatexValidityConditionView.php
  templates/api/regulations.xml.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
Labels: To review

#693 Implement PR+abs
  config/validator/Application/Regulation/Command/SaveLocationCommand.xml
  src/Application/Exception/AbscissaOutOfRangeException.php
  src/Application/Exception/EndAbscissaOutOfRangeException.php
  src/Application/Exception/GeocodingFailureException.php
  src/Application/Exception/RoadGeocodingFailureException.php
  src/Application/Exception/StartAbscissaOutOfRangeException.php
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Command/Location/SaveLocationCommand.php
  src/Application/Regulation/Command/Location/SaveLocationCommandHandler.php
  src/Application/Regulation/Command/SaveMeasureCommandHandler.php
  src/Application/Regulation/View/LocationView.php
  src/Application/Regulation/View/Measure/LocationView.php
  src/Application/Regulation/View/Measure/MeasureView.php
  src/Application/RoadGeocoderInterface.php
  src/Application/RoadSectionMakerInterface.php
  src/Domain/Regulation/Enum/RoadSideEnum.php
  src/Domain/Regulation/Location.php
  src/Domain/Regulation/Repository/LocationRepositoryInterface.php
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/Adapter/RoadSectionMaker.php
  src/Infrastructure/Controller/Regulation/Fragments/AddMeasureController.php
  src/Infrastructure/Controller/Regulation/Fragments/GetDepartmentalRoadCompletionFragmentController.php
  src/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureController.php
  src/Infrastructure/Form/Regulation/LocationFormType.php
  src/Infrastructure/Persistence/Doctrine/BdTopoMigrations/Version20240327135054.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Location.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240403140624.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  templates/regulation/_location_house_numbers.html.twig
  templates/regulation/_reference_points.html.twig
  templates/regulation/export.md.twig
  templates/regulation/fragments/_measure.html.twig
  templates/regulation/fragments/_measure_form.html.twig
  templates/regulation/fragments/_road_numbers_completions.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetDepartmentalRoadCompletionFragmentControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
  tests/Mock/BdTopoRoadGeocoderMock.php
  tests/Unit/Application/Regulation/Command/Location/SaveLocationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Query/Measure/GetMeasuresQueryHandlerTest.php
  tests/Unit/Domain/Regulation/LocationTest.php
  tests/Unit/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
  tests/Unit/Infrastructure/Adapter/RoadSectionMakerTest.php
  tools/bdtopo_update.config.json
  translations/messages.fr.xlf
  translations/validators.fr.xlf
Labels: To review

#720 Remove unused restriction types
  config/validator/Application/Regulation/Command/SaveMeasureCommand.xml
  docs/adr/002_mcd.md
  src/Domain/Regulation/Enum/MeasureTypeEnum.php
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240411074701.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveMeasureCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveMeasureCommandTest.php
  translations/messages.fr.xlf
Labels: To review

#723 Remove playwright
  .github/workflows/ci.yml
  .gitignore
  Makefile
  docker-compose.yml
  docker/php/Dockerfile
  docs/tools/quality.md
  package-lock.json
  package.json
  playwright.config.js
  tests/e2e/auth.setup.js
  tests/e2e/general_info_form.spec.js
  tests/e2e/list.mobile.spec.js
  tests/e2e/list.spec.js
  tests/e2e/pages/regulation_order.page.js
  tests/e2e/regulation_edit.spec.js
  tests/e2e/regulation_publish.spec.js
Labels: tech, To review

#655 Update deps
  composer.json
  composer.lock
  package-lock.json
  src/Application/Exception/GeocodingFailureException.php
  src/Application/Regulation/Command/SaveMeasureCommand.php
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommand.php
  src/Domain/Condition/VehicleSet.php
  src/Domain/Regulation/Location.php
  src/Domain/Regulation/RegulationOrder.php
  src/Infrastructure/FeatureFlagService.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrderRecord.orm.xml
  src/Infrastructure/Persistence/Doctrine/Repository/Country/France/CityRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/MeasureRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Twig/AppExtension.php
  tests/Unit/Infrastructure/EudonetParis/EudonetParisTransformerTest.php
Labels: tech, To review

#731 Retire les dates de fin sur les arrêtés BAC-IDF
  src/Infrastructure/BacIdf/BacIdfTransformer.php
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240416135713.php
  tests/Unit/Infrastructure/BacIdf/BacIdfTransformerTest.php
Labels: To review

#725 Améliore le champ Ville
  assets/controllers/autocomplete_controller.js
  assets/styles/components/autocomplete.scss
  config/validator/Application/Regulation/Command/SaveLocationCommand.xml
  src/Infrastructure/Form/Regulation/LocationFormType.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  translations/validators.fr.xlf
Labels: To review

#721 Rework CIFS export using entities
  src/Application/Cifs/PolylineMakerInterface.php
  src/Application/Regulation/Query/GetCifsIncidentsQueryHandler.php
  src/Application/Regulation/View/CifsIncidentView.php
  src/Infrastructure/Cifs/PolylineMaker.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/api/regulations/cifs.xml.twig
  tests/Integration/Infrastructure/Cifs/PolylineMakerTest.php
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
Labels: To review

#736 Corrige le parsing des organisations avec tiret
  src/Infrastructure/Persistence/Cache/Repository/Regulation/AdministratorRepository.php
  tests/Integration/Infrastructure/Repository/AdministratorRepositoryTest.php
Labels: Bug

#735 Fix invalid period
  config/validator/Application/Regulation/Command/SavePeriodCommand.xml
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  translations/validators.fr.xlf
Labels: To review

#707 Précise le message d'erreur en cas de numéros sur des morceaux disjoints
  config/validator/Application/Regulation/Command/SaveLocationCommand.xml
  src/Application/Exception/LaneGeocodingFailureException.php
  src/Infrastructure/Adapter/LaneSectionMaker.php
  src/Infrastructure/Controller/Regulation/Fragments/AddMeasureController.php
  src/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureController.php
  templates/regulation/fragments/_measure_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
  tests/Mock/APIAdresseMockClient.php
  tests/Mock/BdTopoRoadGeocoderMock.php
  translations/validators.fr.xlf
Labels: To review

#740 Utilise affichage plus robuste des noms de voie BD TOPO
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
Labels: Bug, tech

#750 Inverser l'affichage des boutons de connexion et de création de compte
  templates/common/header.html.twig
Labels: UI / UX, To review

#748 Renommer le bouton d'accès aux arrêtés de circulation depuis le header
  templates/common/header.html.twig
  tests/Integration/Infrastructure/Controller/LandingControllerTest.php
  tests/Integration/Infrastructure/Controller/LoginControllerTest.php
Labels: UI / UX, To review

#742 Implémente une réinitialisation des champs de section
  assets/controllers/reset_controller.js
  assets/lib.js
  templates/regulation/fragments/_measure_form.html.twig
Labels: UI / UX, To review

#745 Rediriger l'utilisateur vers la landing page au clique sur le logo DiaLog
  templates/common/footer.html.twig
  templates/common/header.html.twig
  templates/layouts/_base.html.twig
Labels: UI / UX, To review
