Repository MTES-MCT/dialog, pull requests merged in 2024-09, with the labels that each got.

#937 🚀 Update to SF 7.1
  composer.json
  composer.lock
  config/packages/doctrine.yaml
  package-lock.json
  src/Infrastructure/Litteralis/LitteralisPeriodParser.php
Labels: To review

#926 Configure l'import automatique des données Litteralis MEL
  .github/workflows/litteralis_mel_import.yml
  Makefile
  docs/tools/eudonet_paris.md
  docs/tools/github_actions.md
  docs/tools/litteralis.md
Labels: tech, To review

#928 Implémente les filtres "Identifiant", "Organisation", "Statut" et "Type d'arrêté" de la vue liste
  assets/customElements/auto_form.js
  assets/customElements/index.js
  assets/styles/app.scss
  assets/styles/customElements/auto_form.css
  assets/styles/customElements/index.scss
  assets/styles/utilities/gap.css
  assets/styles/utilities/index.scss
  composer.json
  composer.lock
  config/packages/doctrine.yaml
  src/Application/Regulation/Query/GetRegulationsQuery.php
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Application/User/Query/GetOrganizationsQuery.php
  src/Application/User/Query/GetOrganizationsQueryHandler.php
  src/Application/User/View/OrganizationView.php
  src/Domain/Regulation/DTO/RegulationListFiltersDTO.php
  src/Domain/Regulation/Enum/RegulationOrderTypeEnum.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Domain/User/Repository/OrganizationRepositoryInterface.php
  src/Infrastructure/Controller/Regulation/ListRegulationsController.php
  src/Infrastructure/Form/Regulation/RegulationListFiltersFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/Organization/OrganizationRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/common/form/dsfr_theme.html.twig
  templates/regulation/_list_filters_form.html.twig
  templates/regulation/index.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
  tests/Unit/Application/User/Query/GetOrganizationsQueryHandlerTest.php
  translations/messages.fr.xlf
Labels: To review

#936 Manage user role inside organization
  config/validator/Application/User/SaveOrganizationUserCommand.xml
  public/images/roles/ROLE_ORGA_ADMIN.svg
  public/images/roles/ROLE_ORGA_CONTRIBUTOR.svg
  public/images/roles/ROLE_ORGA_PUBLISHER.svg
  src/Application/User/Command/ConvertAccessRequestToUserCommandHandler.php
  src/Application/User/Command/SaveOrganizationUserCommand.php
  src/Application/User/Command/SaveOrganizationUserCommandHandler.php
  src/Application/User/View/OrganizationUserView.php
  src/Domain/User/OrganizationUser.php
  src/Infrastructure/Controller/Admin/OrganizationUserCrudController.php
  src/Infrastructure/Controller/Organization/User/DeleteOrganizationUserController.php
  src/Infrastructure/Controller/Organization/User/EditUserController.php
  src/Infrastructure/Form/User/UserFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OrganizationFixture.php
  templates/organization/user/form.html.twig
  templates/organization/user/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/User/AddUserControllerTest.php
  tests/Integration/Infrastructure/Controller/Organization/User/DeleteOrganizationUserControllerTest.php
  tests/Integration/Infrastructure/Controller/Organization/User/EditUserControllerTest.php
  tests/Integration/Infrastructure/Controller/Organization/User/ListUsersControllerTest.php
  tests/Unit/Application/User/Command/ConvertAccessRequestToUserCommandHandlerTest.php
  tests/Unit/Application/User/Command/SaveOrganizationUserCommandHandlerTest.php
  tests/Unit/Application/User/Query/GetOrganizationUsersQueryHandlerTest.php
  tests/Unit/Domain/User/OrganizationUserTest.php
  translations/messages.fr.xlf
Labels: To review

#945 Add visa model
  docs/adr/002_mcd.md
  src/Domain/Visa/VisaModel.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Visa.VisaModel.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240911074626.php
  tests/Unit/Domain/Visa/VisaModelTest.php
Labels: To review

#944 Refactor: Intègre page et pageSize au DTO
  src/Application/Regulation/Query/GetRegulationsQuery.php
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Domain/Pagination.php
  src/Domain/Regulation/DTO/RegulationListFiltersDTO.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Controller/Regulation/ListRegulationsController.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/_list_filters_form.html.twig
  templates/regulation/index.html.twig
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
Labels: To review

#949 CIFS : traite les créneaux horaires même si pas de jours concernés
  src/Application/Regulation/Query/GetCifsIncidentsQueryHandler.php
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
Labels: Bug, To review

#950 Liste des modèles de visas
  src/Application/Visa/Query/GetOrganizationVisaModelsQuery.php
  src/Application/Visa/Query/GetOrganizationVisaModelsQueryHandler.php
  src/Application/Visa/View/VisaModelView.php
  src/Domain/Visa/Repository/VisaModelRepositoryInterface.php
  src/Infrastructure/Controller/Organization/Visa/ListVisaModelsController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/VisaModelFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Visa/VisaModelRepository.php
  templates/organization/_menu.html.twig
  templates/organization/user/form.html.twig
  templates/organization/user/index.html.twig
  templates/organization/visa_model/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/Visa/ListVisaModelsControllerTest.php
  tests/Unit/Application/Visa/Query/GetOrganizationVisaModelsQueryHandlerTest.php
  translations/messages.fr.xlf
Labels: To review

#956 Fix list visa markup
  templates/organization/visa_model/index.html.twig
Labels: To review

#955 Add visa model
  assets/styles/components/dsfr-extensions/icon.scss
  config/validator/Application/VisaModel/SaveVisaModelCommand.xml
  public/images/icons/check.svg
  src/Application/VisaModel/Command/SaveVisaModelCommand.php
  src/Application/VisaModel/Command/SaveVisaModelCommandHandler.php
  src/Application/VisaModel/Query/GetOrganizationVisaModelsQuery.php
  src/Application/VisaModel/Query/GetOrganizationVisaModelsQueryHandler.php
  src/Application/VisaModel/View/VisaModelView.php
  src/Domain/VisaModel/Repository/VisaModelRepositoryInterface.php
  src/Domain/VisaModel/VisaModel.php
  src/Infrastructure/Controller/Organization/VisaModel/AddVisaModelController.php
  src/Infrastructure/Controller/Organization/VisaModel/ListVisaModelsController.php
  src/Infrastructure/Form/User/VisaModelFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/VisaModelFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/VisaModel.VisaModel.orm.xml
  src/Infrastructure/Persistence/Doctrine/Repository/VisaModel/VisaModelRepository.php
  templates/organization/_menu.html.twig
  templates/organization/visa_model/form.html.twig
  templates/organization/visa_model/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/VisaModel/AddVisaControllerTest.php
  tests/Integration/Infrastructure/Controller/Organization/VisaModel/ListVisaModelsControllerTest.php
  tests/Unit/Application/VisaModel/Query/GetOrganizationVisaModelsQueryHandlerTest.php
  tests/Unit/Domain/VisaModel/VisaModelTest.php
  translations/messages.fr.xlf
Labels: To review

#958 Edit visa model
  src/Application/VisaModel/Command/SaveVisaModelCommand.php
  src/Application/VisaModel/Command/SaveVisaModelCommandHandler.php
  src/Application/VisaModel/Query/GetVisaModelQuery.php
  src/Application/VisaModel/Query/GetVisaModelQueryHandler.php
  src/Domain/VisaModel/Exception/VisaModelNotFoundException.php
  src/Domain/VisaModel/Repository/VisaModelRepositoryInterface.php
  src/Domain/VisaModel/VisaModel.php
  src/Infrastructure/Controller/Organization/VisaModel/EditVisaModelController.php
  src/Infrastructure/Persistence/Doctrine/Repository/VisaModel/VisaModelRepository.php
  templates/organization/visa_model/form.html.twig
  templates/organization/visa_model/index.html.twig
  tests/Integration/Infrastructure/Controller/Organization/VisaModel/AddVisaModelControllerTest.php
  tests/Integration/Infrastructure/Controller/Organization/VisaModel/EditVisaModelControllerTest.php
  tests/Unit/Application/User/Command/SaveOrganizationUserCommandHandlerTest.php
  tests/Unit/Application/VisaModel/Command/SaveVisaModelCommandHandlerTest.php
  tests/Unit/Application/VisaModel/Query/GetVisaModelQueryHandlerTest.php
  tests/Unit/Domain/VisaModel/VisaModelTest.php
Labels: To review

#942 Utilise ST_ApproximateMedialAxis pour le calcul des linéaires Litteralis
  config/packages/jsor_doctrine_postgis.yaml
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/Persistence/Doctrine/BdTopoMigrations/Version20240917103338.php
  src/Infrastructure/Persistence/Doctrine/PostGIS/Functions/ST_ApproximateMedialAxis.php
  tests/Integration/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
Labels: tech, To review

#961 Simplify csrf token managment thanks to Symfony 7.1 and PHP attributes
  src/Infrastructure/Controller/Organization/User/DeleteOrganizationUserController.php
  src/Infrastructure/Controller/Regulation/DeleteRegulationController.php
  src/Infrastructure/Controller/Regulation/DuplicateRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/DeleteMeasureFragmentController.php
  src/Infrastructure/Controller/Regulation/PublishRegulationController.php
  templates/organization/user/index.html.twig
  templates/regulation/_items.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_measure_delete_form.html.twig
  templates/regulation/fragments/_publication_button.html.twig
  tests/Integration/Infrastructure/Controller/Organization/User/DeleteOrganizationUserControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/DeleteRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/DuplicateRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/DeleteMeasureFragmentControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/PublishRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
Labels: tech, To review

#962 Improve model_visas listing rendering
  templates/organization/visa_model/index.html.twig
Labels: To review

#965 Add admin link
  templates/my_area/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/IndexControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#966 Remove model visa
  src/Application/VisaModel/Command/DeleteVisaModelCommand.php
  src/Application/VisaModel/Command/DeleteVisaModelCommandHandler.php
  src/Domain/VisaModel/Repository/VisaModelRepositoryInterface.php
  src/Infrastructure/Controller/MyArea/Organization/User/DeleteOrganizationUserController.php
  src/Infrastructure/Controller/MyArea/Organization/VisaModel/DeleteVisaModelController.php
  src/Infrastructure/Persistence/Doctrine/Repository/VisaModel/VisaModelRepository.php
  templates/my_area/organization/visa_model/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/VisaModel/DeleteVisaModelControllerTest.php
  tests/Unit/Application/VisaModel/Command/DeleteVisaModelCommandHandlerTest.php
  translations/messages.fr.xlf
Labels: To review

#960 Expose les géométries Litteralis dans le flux CIFS
  src/Application/Cifs/PolylineMakerInterface.php
  src/Application/Regulation/Query/GetCifsIncidentsQueryHandler.php
  src/Domain/Regulation/Location/Location.php
  src/Infrastructure/Cifs/PolylineMaker.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MeasureFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderRecordFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/Map/Fragment/MapDataControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Integration/Infrastructure/Repository/RegulationOrderRecordRepositoryTest.php
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
  tests/Unit/Domain/Regulation/Location/LocationTest.php
Labels: To review

#967 VisaModel administration
  config/validator/Domain/VisaModel/VisaModel.xml
  src/Application/VisaModel/Command/SaveVisaModelCommandHandler.php
  src/Domain/VisaModel/VisaModel.php
  src/Infrastructure/Controller/Admin/DashboardController.php
  src/Infrastructure/Controller/Admin/VisaModelCrudController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/VisaModelFixture.php
  tests/Integration/Infrastructure/Controller/Admin/VisaModelCrudControllerTest.php
  tests/Unit/Application/VisaModel/Command/SaveVisaModelCommandHandlerTest.php
  tests/Unit/Domain/VisaModel/VisaModelTest.php
  translations/messages.fr.xlf
Labels: To review

#968 Active l'import automatique Litteralis MEL
  .github/workflows/litteralis_mel_import.yml
Labels: To review

#957 Extrait le code de reporting de l'intégration Litteralis
  config/services.yaml
  src/Infrastructure/IntegrationReport/CommonRecordEnum.php
  src/Infrastructure/IntegrationReport/RecordTypeEnum.php
  src/Infrastructure/IntegrationReport/ReportFormatter.php
  src/Infrastructure/IntegrationReport/Reporter.php
  src/Infrastructure/Litteralis/LitteralisClient.php
  src/Infrastructure/Litteralis/LitteralisExecutor.php
  src/Infrastructure/Litteralis/LitteralisExtractor.php
  src/Infrastructure/Litteralis/LitteralisPeriodParser.php
  src/Infrastructure/Litteralis/LitteralisRecordEnum.php
  src/Infrastructure/Litteralis/LitteralisReporter.php
  src/Infrastructure/Litteralis/LitteralisReporterFactory.php
  src/Infrastructure/Litteralis/LitteralisTransformer.php
  src/Infrastructure/MEL/MELExecutor.php
  src/Infrastructure/Symfony/Command/MELImportCommand.php
  tests/Integration/Infrastructure/IntegrationReport/ReportFormatterTest.php
  tests/Integration/Infrastructure/Litteralis/LitteralisReportFormatterTest.php
  tests/Unit/Infrastructure/IntegrationReport/ReporterTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisClientTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExecutorTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExtractorTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisPeriodParserTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisReporterFactoryTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisTransformerTest.php
  tests/Unit/Infrastructure/Symfony/Command/MELImportCommandTest.php
  translations/messages.fr.xlf
Labels: To review

#972 Inclure date de fin arrêté dans CIFS si pas de périodes
  src/Application/DateUtilsInterface.php
  src/Application/Regulation/Query/GetCifsIncidentsQueryHandler.php
  src/Infrastructure/Adapter/DateUtils.php
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Mock/DateUtilsMock.php
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
  tests/Unit/Infrastructure/Adapter/DateUtilsTest.php
Labels: To review

#970 Remonte le viewport en cas d'erreur dans un formulaire
  assets/controllers/viewport_controller.js
  templates/common/form/dsfr_theme.html.twig
Labels: To review

#976 Update deps
  composer.lock
  package-lock.json
Labels: tech, To review

#975 Affiche le label RawGeoJSON dans la liste
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Application/Regulation/View/RawGeoJSONView.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/_item_location.html.twig
  templates/regulation/_items.html.twig
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
Labels: To review

#978 RegulationOrder visas model
  src/Domain/Regulation/RegulationOrder.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240926100023.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
Labels: To review

#979 Ajoute CI pour import auto Fougères
  .github/workflows/litteralis_fougeres_import.yml
  Makefile
Labels: To review

#977 Carto : retravaille la popup
  assets/customElements/map.js
  assets/styles/map.scss
  assets/styles/utilities/gap.css
  assets/styles/utilities/grow.css
  src/Infrastructure/Twig/AppExtension.php
  templates/map/fragments/location_popup.html.twig
  templates/regulation/_measure_title.html.twig
  templates/regulation/_vehicle_set.html.twig
  templates/regulation/export.md.twig
  templates/regulation/fragments/_measure.html.twig
  templates/regulation/fragments/_measure_form.html.twig
  tests/Integration/Infrastructure/Controller/Map/Fragment/GetLocationControllerTest.php
  tests/Integration/Infrastructure/Templates/VehicleSetTemplateTest.php
  tests/Unit/Infrastructure/Twig/AppExtensionTest.php
  translations/messages.fr.xlf
  webpack.config.js
Labels: To review
