Repository MTES-MCT/dialog, pull requests merged in 2024-11, with the labels that each got.

#1050 Correctif suite à réimport BDTOPO
  tests/Integration/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
  tools/bdtopo_update
Labels: To review

#1049 Renomme madeIn en placeOfSignature
  src/Domain/Organization/SigningAuthority/SigningAuthority.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Organization.SigningAuthority.SigningAuthority.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20241031170829.php
  tests/Unit/Domain/User/SigningAuthorityTest.php
Labels: To review

#1052 Fait renvoyer array aux getters qui renvoient ?array
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Domain/Regulation/RegulationOrder.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
Labels: tech, To review

#1041 Ajout d'un lien vers les modèles de visas
  src/Infrastructure/Controller/Regulation/Fragments/VisaModelFragmentController.php
  src/Infrastructure/Controller/Regulation/Fragments/VisaModelsOptionsFragmentController.php
  templates/my_area/organization/visa_model/index.html.twig
  templates/regulation/_general_info_form.html.twig
  templates/regulation/_visa_models_management_notice.html.twig
  templates/regulation/fragments/visa_model.stream.html.twig
  templates/regulation/fragments/visa_models_options.stream.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/VisaModel/ListVisaModelsControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/SaveRegulationGeneralInfoControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/VisaModelFragmentControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/VisaModelsOptionsFragmentControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1053 Carte : augmente le zoom pour les adresses
  assets/customElements/map_search_form.js
Labels: To review

#1057 Security dependancies fix (CVE)
  composer.lock
  package-lock.json
Labels: To review, Critique

#1060 Mise à jour du Makefile
  Makefile
Labels: To review

#1047 Signing authority form
  config/validator/Application/SigningAuthority/SaveSigningAuthorityCommand.xml
  public/images/signing_authority.png
  src/Application/Organization/SigningAuthority/Command/SaveSigningAuthorityCommand.php
  src/Application/Organization/SigningAuthority/Command/SaveSigningAuthorityCommandHandler.php
  src/Application/Organization/SigningAuthority/Query/GetSigningAuthorityByOrganizationQuery.php
  src/Application/Organization/SigningAuthority/Query/GetSigningAuthorityByOrganizationQueryHandler.php
  src/Domain/Organization/SigningAuthority/Repository/SigningAuthorityRepositoryInterface.php
  src/Domain/Organization/SigningAuthority/SigningAuthority.php
  src/Infrastructure/Controller/MyArea/Organization/SigningAuthority/EditSigningAuthorityController.php
  src/Infrastructure/Form/Organization/SigningAuthorityFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/SigningAuthority/SigningAuthorityRepository.php
  templates/my_area/organization/_menu.html.twig
  templates/my_area/organization/signing_authority/form.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/SigningAuthority/EditSigningAuthorityControllerTest.php
  tests/Unit/Application/Organization/SigningAuthority/Command/SaveSigningAuthorityCommandHandlerTest.php
  tests/Unit/Application/Organization/SigningAuthority/Query/GetSigningAuthorityByOrganizationQueryHandlerTest.php
  tests/Unit/Application/Organization/VisaModel/Command/DeleteVisaModelCommandHandlerTest.php
  tests/Unit/Application/Organization/VisaModel/Command/DuplicateVisaModelCommandHandlerTest.php
  tests/Unit/Application/Organization/VisaModel/Command/SaveVisaModelCommandHandlerTest.php
  tests/Unit/Application/Organization/VisaModel/Query/GetVisaModelQueryHandlerTest.php
  tests/Unit/Application/Organization/VisaModel/Query/GetVisaModelsQueryHandlerTest.php
  tests/Unit/Domain/User/SigningAuthorityTest.php
  translations/messages.fr.xlf
Labels: To review

#1065 Signing authority export
  src/Infrastructure/Controller/Regulation/ExportRegulationController.php
  templates/regulation/_overall_period.html.twig
  templates/regulation/export.md.twig
Labels: To review

#1074 Corrige des assertions suite à màj BDTOPO
  tests/Integration/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
Labels: To review

#1068 Ajout du logo dans l'administration de l'organisation
  .env
  .env.test
  .github/workflows/ci.yml
  .gitignore
  .gitkeep
  assets/styles/components/card.css
  composer.json
  composer.lock
  config/bundles.php
  config/packages/flysystem.yaml
  config/validator/Application/Organization/Logo/SaveOrganizationLogoCommand.xml
  docs/tools/README.md
  docs/tools/s3.md
  public/images/placeholder-16x9.png
  public/images/placeholder-logo.svg
  src/Application/Organization/Logo/Command/SaveOrganizationLogoCommand.php
  src/Application/Organization/Logo/Command/SaveOrganizationLogoCommandHandler.php
  src/Application/StorageInterface.php
  src/Domain/User/Organization.php
  src/Infrastructure/Adapter/Storage.php
  src/Infrastructure/Controller/MyArea/Organization/EditOrganizationLogoController.php
  src/Infrastructure/Form/Organization/LogoFormType.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Organization.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20241112162221.php
  symfony.lock
  templates/my_area/organization/_menu.html.twig
  templates/my_area/organization/logo.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/EditOrganizationLogoControllerTest.php
  tests/Unit/Application/Organization/Logo/Command/SaveOrganizationLogoCommandHandlerTest.php
  tests/Unit/Domain/User/OrganizationTest.php
  tests/Unit/Infrastructure/Adapter/StorageTest.php
  tests/fixtures/dialog_export.docx
  tests/fixtures/file_too_large.pdf
  tests/fixtures/logo.png
  translations/messages.fr.xlf
Labels: To review

#1070 Calcule les PR+abs selon la méthode de l'API-DSCR
  src/Application/RoadGeocoderInterface.php
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/Adapter/RoadSectionMaker.php
  src/Infrastructure/Persistence/Doctrine/BdTopoMigrations/Version20241118140024.php
  tests/Integration/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
  tests/Unit/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
  tests/Unit/Infrastructure/Adapter/RoadSectionMakerTest.php
  tools/bdtopo_update
  tools/bdtopo_update.config.json
Labels: To review

#1080 Logo form refactoring
  assets/controllers/form_upload_controller.js
  assets/styles/reset.css
  src/Infrastructure/Form/Organization/LogoFormType.php
  templates/common/form/dsfr_theme.html.twig
  templates/my_area/organization/logo.html.twig
  translations/messages.fr.xlf
Labels: To review

#1085 Rafraîchit le logo après upload
  src/Application/Organization/Logo/Command/SaveOrganizationLogoCommandHandler.php
  src/Application/StorageInterface.php
  src/Infrastructure/Adapter/Storage.php
  tests/Unit/Application/Organization/Logo/Command/SaveOrganizationLogoCommandHandlerTest.php
Labels: UI / UX, To review

#1084 Aligne texte du blog à gauche
  blog/public/css/index.css
Labels: UI / UX, To review
