Repository MTES-MCT/dialog, pull requests merged in 2024-12, with the labels that each got.

#1089 Export logo & Word normalisation
  Aptfile
  data/regulation-order-template.docx
  docker/php/Dockerfile
  src/Application/Regulation/Query/GetGeneralInfoQueryHandler.php
  src/Application/Regulation/View/GeneralInfoView.php
  src/Application/StorageInterface.php
  src/Infrastructure/Adapter/Storage.php
  src/Infrastructure/Controller/MyArea/Organization/EditOrganizationLogoController.php
  src/Infrastructure/Controller/MyArea/Organization/OrganizationDetailController.php
  src/Infrastructure/Controller/Regulation/ExportRegulationController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OrganizationFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  templates/regulation/export.md.twig
  tests/Unit/Application/Regulation/Query/GetGeneralInfoQueryHandlerTest.php
  tests/Unit/Application/Regulation/View/GeneralInfoViewTest.php
  tests/Unit/Infrastructure/Adapter/StorageTest.php
Labels: To review

#1093 Remove blog from CI
  Makefile
Labels: tech

#1103 Evite les GeometryCollection à 1 seul élément
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/Adapter/LineSectionMaker.php
  src/Infrastructure/BacIdf/BacIdfTransformer.php
  src/Infrastructure/Persistence/Doctrine/BdTopoMigrations/Version20241204152107.php
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20241204142019.php
  tests/Integration/Infrastructure/Adapter/LineSectionMakerTest.php
  tests/Unit/Infrastructure/BacIdf/BacIdfTransformerTest.php
Labels: tech, To review

#1101 Ajoute des commandes utilitaires createdb, usedb, dropdb, listdb
  Makefile
  docs/tools/db.md
Labels: tech, To review

#1106 Corrige les caractères encodés dans la popup carte
  src/Infrastructure/Twig/AppExtension.php
  tests/Unit/Infrastructure/Twig/AppExtensionTest.php
Labels: Bug, To review

#1108 Ajout du filtre "Mes organisations" sur la liste des restrictions
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Domain/Regulation/DTO/RegulationListFiltersDTO.php
  src/Infrastructure/Controller/Regulation/ListRegulationsController.php
  src/Infrastructure/Form/Regulation/RegulationListFiltersFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1107 Précise que "Données brutes GeoJSON" doit contenir une géométrie
  config/validator/Application/Regulation/Command/SaveRawGeoJSONCommand.xml
  src/Infrastructure/Validator/ValidGeoJsonGeometryConstraint.php
  src/Infrastructure/Validator/ValidGeoJsonGeometryConstraintValidator.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
  translations/validators.fr.xlf
Labels: To review

#1115 Fix GeneralInfoView when a subject is null
  src/Application/Regulation/View/GeneralInfoView.php
Labels: Bug, Critique

#1105 Supprime heure de début pour arrêté permanent
  config/validator/Application/Regulation/Command/SavePeriodCommand.xml
  src/Application/Regulation/Command/Period/SavePeriodCommandHandler.php
  src/Application/Regulation/View/PeriodView.php
  src/Infrastructure/Form/Regulation/PeriodFormType.php
  templates/regulation/_period.html.twig
  templates/regulation/fragments/_measure_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/DuplicateRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  tests/Unit/Application/Regulation/Command/Period/SavePeriodCommandHandlerTest.php
Labels: To review

#1109 Ajoute Sens concerné sur les routes départementales et nationales
  src/Application/Regulation/Command/DuplicateMeasureCommandHandler.php
  src/Application/Regulation/Command/Location/SaveNumberedRoadCommand.php
  src/Application/Regulation/Command/Location/SaveNumberedRoadCommandHandler.php
  src/Application/Regulation/Query/Location/GetNumberedRoadGeometryQueryHandler.php
  src/Application/RoadSectionMakerInterface.php
  src/Domain/Regulation/Location/NumberedRoad.php
  src/Infrastructure/Adapter/RoadSectionMaker.php
  src/Infrastructure/Form/Regulation/NamedStreetFormType.php
  src/Infrastructure/Form/Regulation/NumberedRoadFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Location.NumberedRoad.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20241205151339.php
  templates/regulation/fragments/_measure_form.html.twig
  tests/Unit/Application/Regulation/Command/DuplicateMeasureCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/Location/SaveNumberedRoadCommandHandlerTest.php
  tests/Unit/Domain/Regulation/Location/NumberedRoadTest.php
  tests/Unit/Infrastructure/Adapter/RoadSectionMakerTest.php
  translations/messages.fr.xlf
Labels: To review

#1116 Exécute l'export Metabase depuis PHP
  .env
  .github/workflows/ci.yml
  .github/workflows/metabase_export.yml
  .github/workflows/metabase_migrate.yml
  Makefile
  config/packages/doctrine.yaml
  config/packages/metabase/doctrine_migrations.yaml
  docs/tools/metabase.md
  phpunit.xml.dist
  src/Domain/Statistics/Repository/StatisticsRepositoryInterface.php
  src/Domain/User/Repository/UserRepositoryInterface.php
  src/Domain/User/User.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/UserFixture.php
  src/Infrastructure/Persistence/Doctrine/MetabaseMigrations/Version20241216132451.php
  src/Infrastructure/Persistence/Doctrine/Repository/Statistics/StatisticsRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/UserRepository.php
  src/Infrastructure/Symfony/Command/RunMetabaseExportCommand.php
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Integration/Infrastructure/Symfony/Command/RunMetabaseExportCommandTest.php
  tools/metabase-export.sh
  tools/metabase-export.sql
Labels: To review

#1121 Configure le tunnel SSH pour les migrations Metabase
  .github/workflows/metabase_migrate.yml
  Makefile
Labels: Bug, To review

#1120 Intègre les indicateurs existants dans Metabase
  src/Domain/Statistics/Repository/StatisticsRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/MetabaseMigrations/Version20241216142341.php
  src/Infrastructure/Persistence/Doctrine/Repository/Statistics/StatisticsRepository.php
  src/Infrastructure/Symfony/Command/RunMetabaseExportCommand.php
  tests/Integration/Infrastructure/Symfony/Command/RunMetabaseExportCommandTest.php
Labels: To review

#1118 Création d'une dropdown avec les catégories de véhicules lourds
  assets/styles/utilities/dsfr-extensions/sizing.css
  src/Domain/Condition/VehicleSet.php
  src/Infrastructure/Form/Regulation/VehicleSetFormType.php
  templates/regulation/_vehicle_set_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1127 Enregistre la date de création de l'organisation
  src/Application/User/Command/ConvertAccessRequestToUserCommandHandler.php
  src/Application/User/Command/SaveOrganizationCommandHandler.php
  src/Domain/User/Organization.php
  src/Infrastructure/Controller/Admin/OrganizationCrudController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OrganizationFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Organization.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20241219094151.php
  tests/Unit/Application/User/Command/ConvertAccessRequestToUserCommandHandlerTest.php
  tests/Unit/Application/User/Command/SaveOrganizationCommandHandlerTest.php
  tests/Unit/Domain/User/OrganizationTest.php
Labels: To review
