Repository MTES-MCT/dialog, pull requests merged in 2024-10, with the labels that each got.

#982 Corrige la commande Makefile de l'import Fougeres
  Makefile
Labels: Bug, To review

#963 Affiche nom de l'intégration et orga cible dans rapport d'intégration
  src/Infrastructure/IntegrationReport/CommonRecordEnum.php
  src/Infrastructure/IntegrationReport/ReportFormatter.php
  src/Infrastructure/IntegrationReport/Reporter.php
  src/Infrastructure/Litteralis/Fougeres/FougeresExecutor.php
  src/Infrastructure/Litteralis/LitteralisExecutor.php
  src/Infrastructure/Litteralis/MEL/MELExecutor.php
  tests/Integration/Infrastructure/IntegrationReport/ReportFormatterTest.php
  tests/Unit/Infrastructure/IntegrationReport/ReporterTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExecutorTest.php
  translations/messages.fr.xlf
Labels: To review

#983 Ajoute une recherche de lieu à la carte
  .env
  assets/customElements/index.js
  assets/customElements/map.js
  assets/customElements/map_search_form.js
  config/packages/framework.yaml
  config/packages/security.yaml
  config/services.yaml
  src/Application/MapGeocoderInterface.php
  src/Infrastructure/Adapter/IgnMapGeocoder.php
  src/Infrastructure/Controller/Map/Fragments/MapSearchController.php
  templates/map/_search_form.html.twig
  templates/map/fragments/search_results.html.twig
  templates/map/map.html.twig
  tests/Integration/Infrastructure/Controller/Map/Fragment/MapSearchControllerTest.php
  tests/Integration/Infrastructure/Controller/Map/MapControllerTest.php
  tests/Mock/IgnGeocoderMockClient.php
  tests/Unit/Infrastructure/Adapter/IgnMapGeocoderTest.php
  translations/messages.fr.xlf
Labels: To review

#996 Display generic models on organisation admin
  src/Application/VisaModel/Command/DeleteVisaModelCommandHandler.php
  src/Application/VisaModel/Command/DuplicateVisaModelCommand.php
  src/Application/VisaModel/Command/DuplicateVisaModelCommandHandler.php
  src/Application/VisaModel/View/VisaModelView.php
  src/Domain/VisaModel/Exception/VisaModelCannotBeDeletedException.php
  src/Infrastructure/Controller/MyArea/Organization/VisaModel/DeleteVisaModelController.php
  src/Infrastructure/Controller/MyArea/Organization/VisaModel/DuplicateVisaModelController.php
  src/Infrastructure/Persistence/Doctrine/Repository/VisaModel/VisaModelRepository.php
  templates/my_area/organization/visa_model/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/VisaModel/ListVisaModelsControllerTest.php
  tests/Unit/Application/VisaModel/Command/DeleteVisaModelCommandHandlerTest.php
  tests/Unit/Application/VisaModel/Command/DuplicateVisaModelCommandHandlerTest.php
  tests/Unit/Application/VisaModel/Query/GetOrganizationVisaModelsQueryHandlerTest.php
Labels: To review

#998 Enregistre une date de dernière activité de l'utilisateur
  src/Application/User/Command/MarkUserAsActiveCommand.php
  src/Application/User/Command/MarkUserAsActiveCommandHandler.php
  src/Domain/User/User.php
  src/Infrastructure/Controller/Admin/UserCrudController.php
  src/Infrastructure/Controller/Regulation/AddRegulationController.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.User.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20241008120435.php
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Unit/Application/User/Command/MarkUserActiveCommandHandlerTest.php
Labels: To review

#997 Visas et Motifs dans un arrêté (Partie 1)
  config/validator/Application/Regulation/Command/SaveRegulationGeneralInfoCommand.xml
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommand.php
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommandHandler.php
  src/Domain/Regulation/RegulationOrder.php
  src/Infrastructure/Form/Regulation/GeneralInfoFormType.php
  templates/regulation/_general_info_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/SaveRegulationGeneralInfoControllerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
  translations/messages.fr.xlf
Labels: To review

#1000 Corrige import Litteralis : Undefined array key "regulationId"
  src/Infrastructure/Litteralis/LitteralisExtractor.php
  src/Infrastructure/Litteralis/LitteralisPeriodParser.php
  src/Infrastructure/Litteralis/LitteralisTransformer.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExtractorTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisTransformerTest.php
Labels: Bug, To review, Significatif

#995 Configure un export Metabase avec l'indicateur "Utilisateurs actifs"
  .github/workflows/metabase_export.yml
  Makefile
  docs/deployment/README.md
  docs/tools/litteralis.md
  docs/tools/metabase.md
  tools/metabase-export.sh
  tools/metabase-export.sql
Labels: To review

#987 improves map filters
  assets/styles/utilities/dsfr-extensions/display.css
  public/images/icons/filter.svg
  src/Domain/Regulation/Repository/LocationRepositoryInterface.php
  src/Infrastructure/Controller/DTO/MapFilterDTO.php
  src/Infrastructure/Controller/Map/Fragments/MapDataController.php
  src/Infrastructure/Form/Map/MapFilterFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  templates/map/map.html.twig
  tests/Integration/Infrastructure/Controller/Map/Fragment/MapDataControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1004 Corrige le géocodage de PR en cas d'ordre de numérisation inversé
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  tests/Integration/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
Labels: To review

#1012 Add visa model detail under select
  assets/styles/variables.css
  src/Infrastructure/Controller/Regulation/Fragments/VisaModelFragmentController.php
  templates/regulation/_general_info_form.html.twig
  templates/regulation/fragments/visa_model.stream.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/VisaModelFragmentControllerTest.php
Labels: To review

#1013 Retire les arrêtés de test inutiles
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderRecordFixture.php
  tests/Integration/Infrastructure/Controller/Regulation/DuplicateRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/SaveRegulationGeneralInfoControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Integration/Infrastructure/Controller/StatisticsControllerTest.php
Labels: tech, To review

#1020 Ajout du lien vers la page de carto
  templates/layouts/public.html.twig
  tests/Integration/Infrastructure/Controller/LandingControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1016 Mise à jour des dépendances
  composer.lock
  package-lock.json
Labels: tech, To review

#1015 Amélioration de l'ux en limitant de nombre de caractères à 50
  src/Infrastructure/Persistence/Doctrine/Fixtures/VisaModelFixture.php
  templates/my_area/organization/visa_model/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/VisaModel/ListVisaModelsControllerTest.php
Labels: UI / UX, To review

#1025 Corrige la duplication d'un arreté
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
Labels: Bug, To review

#1014 Ajout des visas et considérants dans l'export word
  src/Application/Regulation/Query/Visa/GetVisasAndReasonsByRegulationOrderQuery.php
  src/Application/Regulation/Query/Visa/GetVisasAndReasonsByRegulationOrderQueryHandler.php
  src/Application/Regulation/View/GeneralInfoView.php
  src/Application/Regulation/View/VisasAndReasonsView.php
  src/Domain/Regulation/Repository/RegulationOrderRepositoryInterface.php
  src/Infrastructure/Controller/Regulation/ExportRegulationController.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRepository.php
  templates/regulation/export.md.twig
  tests/Unit/Application/Regulation/Query/GetGeneralInfoQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/Visa/GetVisasAndReasonsByRegulationOrderQueryHandlerTest.php
  tests/Unit/Application/Regulation/View/GeneralInfoViewTest.php
Labels: To review

#1024 Refacto navigation bar
  templates/accessRequest.html.twig
  templates/accessibility_statement.html.twig
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/common/header.html.twig
  templates/ecodesign_statement.html.twig
  templates/feedback.html.twig
  templates/forgot-password.html.twig
  templates/index.html.twig
  templates/landing_authorities.html.twig
  templates/landing_digital_services.html.twig
  templates/landing_road_users.html.twig
  templates/layouts/_base.html.twig
  templates/layouts/app.html.twig
  templates/layouts/layout.html.twig
  templates/layouts/public.html.twig
  templates/legal.html.twig
  templates/login.html.twig
  templates/map/map.html.twig
  templates/my_area/index.html.twig
  templates/my_area/organization/user/form.html.twig
  templates/my_area/organization/user/index.html.twig
  templates/my_area/organization/visa_model/form.html.twig
  templates/my_area/organization/visa_model/index.html.twig
  templates/my_area/profile/delete-profile.html.twig
  templates/my_area/profile/edit-password.html.twig
  templates/my_area/profile/index.html.twig
  templates/public/regulation.html.twig
  templates/regulation/create.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/index.html.twig
  templates/statistics.html.twig
  tests/Integration/Infrastructure/Controller/LandingControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Integration/Infrastructure/Controller/Security/LoginControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1028 Retire le fichier inutilisé templates/public/regulation.html.twig
  templates/public/regulation.html.twig
Labels: To review

#1033 Supprime 'Vu' et 'considérant' de l'export word
  templates/regulation/export.md.twig
  tests/Unit/Infrastructure/BacIdf/BacIdfTransformerTest.php
Labels: To review

#1021 Intégration du nouveau header
  public/images/logo.png
  templates/common/header.html.twig
  tests/Unit/Domain/Regulation/RegulationOrderRecordTest.php
  tests/Unit/Domain/User/Specification/CanUserEditOrganizationTest.php
  tests/Unit/Domain/User/Specification/CanUserPublishRegulationTest.php
  translations/messages.fr.xlf
Labels: To review

#1036 Ajout de la page CGU
  src/Infrastructure/Controller/CGUController.php
  templates/cgu.html.twig
  templates/common/footer.html.twig
  tests/Integration/Infrastructure/Controller/CGUControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1035 Ajout de la page vie privée
  src/Infrastructure/Controller/PrivacyController.php
  templates/common/footer.html.twig
  templates/privacy.html.twig
  tests/Integration/Infrastructure/Controller/PrivacyControllerTest.php
Labels: To review

#1042 Corrige les dates de fixtures en UTC
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  templates/api/regulations.xml.twig
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/MyArea/Organization/VisaModel/ListVisaModelsControllerTest.php
Labels: Bug, tech, To review

#1018 Edition de l'organisation en tant qu'administrateur de celle ci
  config/validator/Application/User/SaveOrganizationCommand.xml
  src/Application/User/Command/CreateOrganizationCommandHandler.php
  src/Application/User/Command/SaveOrganizationCommand.php
  src/Application/User/Command/SaveOrganizationCommandHandler.php
  src/Domain/User/Exception/SiretAlreadyExistException.php
  src/Domain/User/Organization.php
  src/Infrastructure/BacIdf/BacIdfTransformer.php
  src/Infrastructure/BacIdf/BacIdfTransformerResult.php
  src/Infrastructure/Controller/MyArea/Organization/EditOrganizationController.php
  src/Infrastructure/Controller/MyArea/Organization/OrganizationDetailController.php
  src/Infrastructure/Form/Organization/OrganizationFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OrganizationFixture.php
  templates/my_area/index.html.twig
  templates/my_area/organization/_menu.html.twig
  templates/my_area/organization/detail.html.twig
  templates/my_area/organization/form.html.twig
  templates/my_area/organization/user/form.html.twig
  templates/my_area/organization/user/index.html.twig
  templates/my_area/organization/visa_model/form.html.twig
  templates/my_area/organization/visa_model/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/EditOrganizationControllerTest.php
  tests/Integration/Infrastructure/Controller/MyArea/Organization/OrganizationDetailControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Integration/Infrastructure/Controller/StatisticsControllerTest.php
  tests/Unit/Application/User/Command/CreateOrganizationCommandHandlerTest.php
  tests/Unit/Application/User/Command/SaveOrganizationCommandHandlerTest.php
  tests/Unit/Infrastructure/BacIdf/BacIdfExecutorTest.php
  tests/Unit/Infrastructure/BacIdf/BacIdfTransformerTest.php
  translations/messages.fr.xlf
  translations/validators.fr.xlf
Labels: To review

#1037 Intègre le dashboard Metabase à la page stats
  .env
  assets/customElements/index.js
  assets/customElements/responsive_iframe.js
  assets/styles/utilities/dsfr-extensions/sizing.css
  composer.json
  composer.lock
  config/packages/nelmio_security.yaml
  config/services.yaml
  docs/deployment/README.md
  docs/tools/metabase.md
  src/Infrastructure/Adapter/JWTEncoder.php
  src/Infrastructure/Adapter/MetabaseEmbedFactory.php
  src/Infrastructure/Controller/StatisticsController.php
  templates/statistics.html.twig
  tests/Integration/Infrastructure/Controller/StatisticsControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1044 Supprime le lien d'édition dans l'organisation DiaLog
  config/packages/twig.yaml
  templates/my_area/organization/detail.html.twig
Labels: To review

#1011 Supprime la saisie de dates globales sur l'arrêté
  config/validator/Application/Regulation/Command/SaveMeasureCommand.xml
  config/validator/Application/Regulation/Command/SaveRegulationGeneralInfoCommand.xml
  docs/tools/litteralis.md
  src/Application/Regulation/Command/DuplicateRegulationCommandHandler.php
  src/Application/Regulation/Command/SaveMeasureCommand.php
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommand.php
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommandHandler.php
  src/Application/Regulation/Query/GetCifsIncidentsQueryHandler.php
  src/Application/Regulation/Query/GetGeneralInfoQueryHandler.php
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/Query/GetRegulationsQueryHandler.php
  src/Domain/Regulation/RegulationOrder.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/BacIdf/BacIdfTransformer.php
  src/Infrastructure/Controller/Regulation/DuplicateRegulationController.php
  src/Infrastructure/Controller/Regulation/RegulationDetailController.php
  src/Infrastructure/EudonetParis/EudonetParisTransformer.php
  src/Infrastructure/Form/Regulation/GeneralInfoFormType.php
  src/Infrastructure/JOP/JOPTransformer.php
  src/Infrastructure/Litteralis/LitteralisRecordEnum.php
  src/Infrastructure/Litteralis/LitteralisTransformer.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MeasureFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20241016130817.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Validator/SaveRegulationGeneralInfoCommandConstraintValidator.php
  templates/regulation/_general_info_form.html.twig
  templates/regulation/_overall_period.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_measure_form.html.twig
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/Map/Fragment/GetLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/DuplicateRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/SaveRegulationGeneralInfoControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveMeasureCommandTest.php
  tests/Unit/Application/Regulation/Command/SaveRegulationGeneralInfoCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveRegulationGeneralInfoCommandTest.php
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetGeneralInfoQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationsQueryHandlerTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
  tests/Unit/Infrastructure/BacIdf/BacIdfTransformerTest.php
  tests/Unit/Infrastructure/EudonetParis/EudonetParisTransformerTest.php
  tests/Unit/Infrastructure/JOP/JOPTransformerTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisTransformerTest.php
  tests/Unit/Infrastructure/Validation/SaveRegulationGeneralInfoCommandConstraintValidatorTest.php
  translations/messages.fr.xlf
  translations/validators.fr.xlf
Labels: To review

#1038 Signing authority model
  config/validator/Application/VisaModel/SaveVisaModelCommand.xml
  config/validator/Domain/VisaModel/VisaModel.xml
  src/Application/Organization/VisaModel/Command/DeleteVisaModelCommand.php
  src/Application/Organization/VisaModel/Command/DeleteVisaModelCommandHandler.php
  src/Application/Organization/VisaModel/Command/DuplicateVisaModelCommand.php
  src/Application/Organization/VisaModel/Command/DuplicateVisaModelCommandHandler.php
  src/Application/Organization/VisaModel/Command/SaveVisaModelCommand.php
  src/Application/Organization/VisaModel/Command/SaveVisaModelCommandHandler.php
  src/Application/Organization/VisaModel/Query/GetVisaModelQuery.php
  src/Application/Organization/VisaModel/Query/GetVisaModelQueryHandler.php
  src/Application/Organization/VisaModel/Query/GetVisaModelsQuery.php
  src/Application/Organization/VisaModel/Query/GetVisaModelsQueryHandler.php
  src/Application/Organization/VisaModel/View/VisaModelView.php
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommandHandler.php
  src/Domain/Organization/SigningAuthority/SigningAuthority.php
  src/Domain/Organization/VisaModel/Exception/VisaModelCannotBeDeletedException.php
  src/Domain/Organization/VisaModel/Exception/VisaModelNotFoundException.php
  src/Domain/Organization/VisaModel/Repository/VisaModelRepositoryInterface.php
  src/Domain/Organization/VisaModel/VisaModel.php
  src/Domain/Regulation/RegulationOrder.php
  src/Infrastructure/Controller/Admin/DashboardController.php
  src/Infrastructure/Controller/Admin/VisaModelCrudController.php
  src/Infrastructure/Controller/MyArea/Organization/VisaModel/AddVisaModelController.php
  src/Infrastructure/Controller/MyArea/Organization/VisaModel/DeleteVisaModelController.php
  src/Infrastructure/Controller/MyArea/Organization/VisaModel/DuplicateVisaModelController.php
  src/Infrastructure/Controller/MyArea/Organization/VisaModel/EditVisaModelController.php
  src/Infrastructure/Controller/MyArea/Organization/VisaModel/ListVisaModelsController.php
  src/Infrastructure/Controller/Regulation/AddRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/SaveGeneralInfoController.php
  src/Infrastructure/Controller/Regulation/Fragments/VisaModelFragmentController.php
  src/Infrastructure/Controller/Regulation/Fragments/VisaModelsOptionsFragmentController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/VisaModelFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Organization.SigningAuthority.SigningAuthority.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Organization.VisaModel.VisaModel.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrder.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20241029090022.php
  src/Infrastructure/Persistence/Doctrine/Repository/VisaModel/VisaModelRepository.php
  tests/Unit/Application/Regulation/Command/DuplicateRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveRegulationGeneralInfoCommandHandlerTest.php
  tests/Unit/Application/VisaModel/Command/DeleteVisaModelCommandHandlerTest.php
  tests/Unit/Application/VisaModel/Command/DuplicateVisaModelCommandHandlerTest.php
  tests/Unit/Application/VisaModel/Command/SaveVisaModelCommandHandlerTest.php
  tests/Unit/Application/VisaModel/Query/GetVisaModelQueryHandlerTest.php
  tests/Unit/Application/VisaModel/Query/GetVisaModelsQueryHandlerTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
  tests/Unit/Domain/User/SigningAuthorityTest.php
  tests/Unit/Domain/VisaModel/VisaModelTest.php
Labels: To review

#1010 Ajout du filtre sur une période
  assets/customElements/map_form.js
  src/Domain/Regulation/Repository/LocationRepositoryInterface.php
  src/Infrastructure/Controller/DTO/MapFilterDTO.php
  src/Infrastructure/Controller/Map/Fragments/MapDataController.php
  src/Infrastructure/Controller/Map/MapController.php
  src/Infrastructure/Form/Map/MapFilterFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  templates/map/map.html.twig
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/Map/Fragment/MapDataControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1045 Corrige le filtre permanent / temporaire : ro.end_date is not defined
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  tests/Integration/Infrastructure/Controller/Map/Fragment/MapDataControllerTest.php
Labels: Bug, To review, Significatif
