Repository MTES-MCT/dialog, pull requests merged in 2024-06, with the labels that each got.

#799 Fix mismatching turbo-stream tags
  templates/regulation/fragments/_measure.added.stream.html.twig
Labels: To review

#798 Ajoute filtres CIFS sur la source et l'identifiant arrêté
  config/services.yaml
  docs/deployment/README.md
  src/Application/Regulation/DTO/CifsFilterSet.php
  src/Application/Regulation/Query/GetCifsIncidentsQueryHandler.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderRecordFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  src/Infrastructure/Symfony/DependencyInjection/CifsFilterSetEnvVarProcessor.php
  tests/Integration/Infrastructure/Controller/Api/cifs-incidents-expected-result.xml
  tests/Integration/Infrastructure/Repository/RegulationOrderRecordRepositoryTest.php
  tests/Unit/Application/Regulation/Query/GetCifsIncidentsQueryHandlerTest.php
  tests/Unit/Infrastructure/Symfony/DependencyInjection/CifsFilterSetEnvVarProcessorTest.php
Labels: To review

#790 Rend accessible le statut required des champs
  assets/styles/components/form.css
  src/Infrastructure/Form/Regulation/NamedStreetFormType.php
  src/Infrastructure/Form/Regulation/NumberedRoadFormType.php
  templates/common/form/dsfr_theme.html.twig
  templates/regulation/fragments/_measure_form.html.twig
  translations/messages.fr.xlf
Labels: Bug, UI / UX, To review

#791 Passe les modales de Stimulus à customElements
  assets/app.js
  assets/controllers/modal_controller.js
  assets/controllers/modal_trigger_controller.js
  assets/customElements/index.js
  assets/customElements/modal_trigger.element.js
  assets/customElements/util.js
  assets/styles/components/index.scss
  assets/styles/components/modal.css
  templates/common/confirmation_modal.html.twig
  templates/regulation/_items.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_measure_delete_form.html.twig
  templates/regulation/fragments/_publication_button.html.twig
  templates/regulation/index.html.twig
Labels: tech, To review

#802 Fix bug on carte page
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
Labels: Bug

#804 Add maplibregl to webpack safelist
  webpack.config.js
Labels: To review

#809 Fix $cifsFilterSet binding
  config/services.yaml
Labels: Bug critique

#810 Carto : gère les gros payloads découpes en plusieurs textNodes
  assets/customElements/map.js
Labels: Bug

#816 Allow to have many administrators
  .env
  config/services.yaml
  docs/deployment/README.md
  docs/tools/admin.md
  src/Infrastructure/Security/Provider/UserProvider.php
  tests/Integration/Infrastructure/Controller/AbstractWebTestCase.php
Labels: To review

#815 Met à jour la déclaration écoconception
  public/files/2024-06-03 - Audit RGESN DiaLog.pdf
  templates/ecodesign_statement.html.twig
Labels: To review

#822 Remove regulation order issue
  docs/adr/002_mcd.md
  src/Domain/Regulation/RegulationOrderIssue.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrderIssue.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20240611085914.php
  tests/Unit/Domain/Regulation/RegulationOrderIssueTest.php
Labels: To review

#826 Carte : personnalisation des boutons de fermeture des popups
  assets/customElements/map.js
  templates/map/fragments/location_popup.html.twig
Labels: To review

#828 Public regulation page
  src/Infrastructure/Controller/Public/PublicRegulationController.php
  templates/map/fragments/location_popup.html.twig
  templates/public/regulation.html.twig
  templates/regulation/_status_badge.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_export_section.html.twig
  tests/Integration/Infrastructure/Controller/Public/PublicRegulationControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#829 Add missing translation keys on _period.html.twig
  templates/regulation/_period.html.twig
Labels: tech, To review

#825 Carte : couche des localisations : zone de clic élargie + largeur du trait qui varie selon le zoom
  assets/customElements/map.js
Labels: To review

#831 Page publique d'un arrêté
  config/packages/security.yaml
  src/Infrastructure/Controller/Public/PublicRegulationController.php
  src/Infrastructure/Controller/Regulation/AbstractRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/GetMeasureController.php
  src/Infrastructure/Controller/Regulation/RegulationDetailController.php
  templates/map/fragments/location_popup.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_measure.added.stream.html.twig
  templates/regulation/fragments/_measure.html.twig
  tests/Integration/Infrastructure/Controller/Public/PublicRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/DeleteRegulationControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
Labels: To review

#834 Pouvoir rechercher une route départementale avec RDXXX
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetDepartmentalRoadCompletionFragmentControllerTest.php
Labels: Bug, To review

#827 Ajout des dates des arrêtés dans les popups de la carte
  templates/map/fragments/location_popup.html.twig
  tests/Integration/Infrastructure/Controller/Map/Fragment/GetLocationControllerTest.php
Labels: To review

#845 Filtre des données de la carte : restrictions temporaires et/ou permanentes : remplacer les boutons radio par des checkboxes
  src/Domain/Regulation/Repository/LocationRepositoryInterface.php
  src/Infrastructure/Controller/DTO/MapFilterDTO.php
  src/Infrastructure/Controller/Map/MapController.php
  src/Infrastructure/Form/Map/MapFilterFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  templates/map/map.html.twig
  translations/messages.fr.xlf
Labels: To review

#850 Active la compression gzip en local
  docker/nginx/default.conf
Labels: tech, To review

#848 Filtre des données de la carte : meilleur affichage
  templates/map/map.html.twig
  translations/messages.fr.xlf
Labels: To review

#852 Optimise les requêtes de la page de détail
  src/Application/Regulation/Query/GetOrganizationUuidByRegulationOrderRecordQuery.php
  src/Application/Regulation/Query/GetOrganizationUuidByRegulationOrderRecordQueryHandler.php
  src/Domain/Regulation/ArrayRegulationMeasures.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Domain/Regulation/Specification/CanOrganizationAccessToRegulation.php
  src/Infrastructure/Controller/Regulation/RegulationDetailController.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/MeasureRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Unit/Application/Regulation/Query/GetOrganizationUuidByRegulationOrderRecordQueryHandlerTest.php
  tests/Unit/Domain/Regulation/Specification/CanOrganizationAccessToRegulationTest.php
Labels: Bug, To review

#853 Affiche les autres types de véhicules dans le DATEX
  docs/spec/datex2/DATEXII_3_Common.xsd
  docs/spec/datex2/DATEXII_3_DiaLogExtension.xsd
  src/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandler.php
  src/Application/Regulation/View/DatexVehicleConditionView.php
  templates/api/regulations.xml.twig
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Unit/Application/Regulation/Query/GetRegulationOrdersToDatexFormatQueryHandlerTest.php
Labels: To review
