Repository MTES-MCT/dialog, pull requests merged in 2025-03, with the labels that each got.

#1224 Corrige l'attribution du rôle utilisateur dans l'organisation
  src/Application/Organization/Command/GetOrCreateOrganizationBySiretCommandHandler.php
  src/Application/Organization/View/GetOrCreateOrganizationView.php
  src/Application/User/Command/ProConnect/CreateProConnectUserCommandHandler.php
  src/Application/User/Command/RegisterCommandHandler.php
  tests/Unit/Application/Organization/Command/GetOrCreateOrganizationBySiretCommandHandlerTest.php
  tests/Unit/Application/User/Command/RegisterCommandHandlerTest.php
Labels: Bug, To review

#1225 Remplace FranceConnect par ProConnect dans le lien du bouton
  templates/proconnect/_auth_widget.html.twig
  translations/messages.fr.xlf
Labels: To review

#1229 Ajout d'un ADR pour le découpage administratif
  docs/adr/010_litteralis.md
  docs/adr/011_administrative_boundaries.md
  docs/adr/README.md
Labels: To review

#1230 Corrige l'impossibilité de saisir un PR 0
  src/Application/Regulation/View/Measure/NumberedRoadView.php
  src/Domain/Regulation/Location/NumberedRoad.php
  src/Infrastructure/Validator/SaveLocationCommandConstraintValidator.php
  templates/regulation/_reference_points.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
  tests/Unit/Domain/Regulation/Location/NumberedRoadTest.php
Labels: Bug, To review

#1231 Complete Organization model with administrative boundaries informations
  src/Domain/Organization/Enum/OrganizationCodeTypeEnum.php
  src/Domain/User/Organization.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Organization.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250306085340.php
  tests/Unit/Domain/User/OrganizationTest.php
Labels: To review

#1232 Adresse authorité signataire définie sur plusieurs lignes
  src/Application/Organization/SigningAuthority/Command/SaveSigningAuthorityCommand.php
  src/Application/Organization/SigningAuthority/Command/SaveSigningAuthorityCommandHandler.php
  src/Domain/Organization/SigningAuthority/SigningAuthority.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/SigningAuthorityFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Organization.SigningAuthority.SigningAuthority.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250306142031.php
  tests/Unit/Domain/User/SigningAuthorityTest.php
Labels: To review

#1238 Remove old account
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250313103531.php
Labels: To review

#1243 Improve organization codes display on administration
  src/Domain/User/Organization.php
  tests/Unit/Domain/User/OrganizationTest.php
Labels: To review

#1245 Corrige la récupération du code INSEE
  src/Domain/User/Repository/OrganizationRepositoryInterface.php
  src/Infrastructure/Adapter/ApiOrganizationFetcher.php
  src/Infrastructure/Controller/Admin/OrganizationCrudController.php
  src/Infrastructure/Persistence/Doctrine/Repository/Organization/OrganizationRepository.php
  src/Infrastructure/Symfony/Command/SyncOrganizationsCodesCommand.php
  tests/Mock/ApiOrganizationFetcherMock.php
  tests/Unit/Infrastructure/Adapter/ApiOrganizationFetcherTest.php
Labels: Bug, To review

#1239 Update dependencies
  composer.lock
  package-lock.json
Labels: tech, To review

#1236 Ajout des nouveaux champs dans la vue du formulaire adresse de l'autorité signataire
  config/validator/Application/SigningAuthority/SaveSigningAuthorityCommand.xml
  src/Application/Organization/SigningAuthority/Command/SaveSigningAuthorityCommand.php
  src/Application/Organization/SigningAuthority/Command/SaveSigningAuthorityCommandHandler.php
  src/Domain/Organization/SigningAuthority/SigningAuthority.php
  src/Infrastructure/Form/Organization/SigningAuthorityFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/SigningAuthorityFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Organization.SigningAuthority.SigningAuthority.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250306142031.php
  templates/my_area/organization/signing_authority/detail.html.twig
  templates/my_area/organization/signing_authority/form.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/SigningAuthority/EditSigningAuthorityControllerTest.php
  tests/Integration/Infrastructure/Controller/MyArea/Organization/SigningAuthority/SigningAuthorityDetailControllerTest.php
  tests/Unit/Application/Organization/SigningAuthority/Command/SaveSigningAuthorityCommandHandlerTest.php
  translations/messages.fr.xlf
Labels: To review

#1244 Display organization map
  assets/controllers/polygon_map_controller.js
  src/Infrastructure/Controller/Admin/OrganizationCrudController.php
  templates/admin/organization/map.html.twig
  templates/bundles/EasyAdminBundle/layout.html.twig
  templates/my_area/organization/detail.html.twig
  translations/messages.fr.xlf
Labels: To review

#1248 fix signing authority fixture
  src/Infrastructure/Persistence/Doctrine/Fixtures/SigningAuthorityFixture.php
Labels: To review

#1249 Ajout de la date de création dans l'admin des organisations
  src/Infrastructure/Controller/Admin/OrganizationCrudController.php
Labels: To review

#1247 Identifiant par défaut lors de la création d'un nouvel arrêté
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommand.php
  src/Application/Regulation/Query/GetRegulationOrderIdentifierQuery.php
  src/Application/Regulation/Query/GetRegulationOrderIdentifierQueryHandler.php
  src/Domain/Regulation/Repository/RegulationOrderRecordRepositoryInterface.php
  src/Infrastructure/Controller/Regulation/AddRegulationController.php
  src/Infrastructure/Controller/Regulation/Fragments/SaveGeneralInfoController.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderRecordRepository.php
  tests/Integration/Infrastructure/Controller/Regulation/AddRegulationControllerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrderIdentifierQueryHandlerTest.php
Labels: To review
