Repository MTES-MCT/dialog, pull requests merged in 2025-04, with the labels that each got.

#1261 Corrige le BacIdfTransformerTest
  src/Infrastructure/Integration/BacIdf/BacIdfTransformer.php
Labels: To review

#1259 Update to SF 7.2.5
  composer.lock
  package-lock.json
Labels: To review

#1257 Fix: Corrige la date de début utilisée à l'affichage initial de la carte
  src/Infrastructure/Controller/Map/Fragments/MapDataController.php
  tests/Integration/Infrastructure/Controller/Map/Fragment/MapDataControllerTest.php
Labels: Bug, To review

#1260 Ajout de la date de création d'un feedback
  src/Application/User/Command/SaveFeedbackCommandHandler.php
  src/Domain/User/Feedback.php
  src/Infrastructure/Controller/Admin/FeedbackCrudController.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Feedback.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250401143108.php
  tests/Unit/Application/User/Command/SaveFeedbackCommandHandlerTest.php
  tests/Unit/Domain/User/FeedbackTest.php
Labels: To review

#1262 Blog : ajout entretien Aurélie
  blog/content/fr/posts/img/aurelie-itw-pic1.png
  blog/content/fr/posts/img/aurelie-itw-pic2.png
  blog/content/fr/posts/img/aurelie-itw-pic3.png
  blog/content/fr/posts/img/aurelie-itw-pic4.png
  blog/content/fr/posts/itw-aurelie-baton.md
  blog/content/fr/posts/itw-florimond-manca.md
  blog/public/css/index.css
Labels: To review

#1263 Ajuste les alt dans itw Aurélie
  blog/content/fr/posts/itw-aurelie-baton.md
Labels: To review

#1258 Ajoute les gestionnaires manquants pour les routes départementales
  data/gestionnaires.txt
  tests/Integration/Infrastructure/Repository/AdministratorRepositoryTest.php
Labels: To review

#1265 Ajout du modèle de données RegulationOrderTemplate
  docs/adr/002_mcd.md
  src/Domain/Regulation/RegulationOrderTemplate.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrderTemplate.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250407092015.php
  tests/Unit/Domain/Regulation/RegulationOrderTemplateTest.php
Labels: To review

#1266 Ajoute la table mailingList dans le modèle de données
  docs/adr/002_mcd.md
  src/Domain/Organization/MailingList/MailingList.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Organization.MailingList.MailingList.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250407142930.php
  tests/Unit/Domain/MailingList/MailingListTest.php
Labels: To review

#1267 Liste des modèles d'arrêté
  src/Application/Regulation/Query/GetRegulationOrderTemplatesQuery.php
  src/Application/Regulation/Query/GetRegulationOrderTemplatesQueryHandler.php
  src/Application/Regulation/View/RegulationOrderTemplateView.php
  src/Domain/Regulation/DTO/RegulationOrderTemplateDTO.php
  src/Domain/Regulation/Repository/RegulationOrderTemplateRepositoryInterface.php
  src/Infrastructure/Controller/MyArea/Organization/RegulationOrderTemplate/ListRegulationOrderTemplatesController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderTemplateFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderTemplateRepository.php
  templates/my_area/organization/_menu.html.twig
  templates/my_area/organization/regulation_order_template/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/RegulationOrderTemplate/ListRegulationOrderTemplatesControllerTest.php
  tests/Unit/Application/Regulation/Query/GetRegulationOrderTemplatesQueryHandlerTest.php
  translations/messages.fr.xlf
Labels: To review

#1269 Traitement des retours de Léa
  tests/Unit/Application/Regulation/Query/GetRegulationOrderTemplatesQueryHandlerTest.php
  translations/messages.fr.xlf
Labels: To review

#1268 Affichage liste de diffusion
  src/Application/Organization/MailingList/Query/GetMailingListQuery.php
  src/Application/Organization/MailingList/Query/GetMailingListQueryHandler.php
  src/Domain/Organization/MailingList/Repository/MailingListRepositoryInterface.php
  src/Infrastructure/Controller/MyArea/Organization/MailingList/RecipientsListController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/MailingListFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/MailingList/MailingListRepository.php
  templates/my_area/organization/mailing_list/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/MailingList/RecipientsListControllerTest.php
  tests/Unit/Application/Organization/MailingList/Query/GetMailingListQueryHandlerTest.php
  translations/messages.fr.xlf
Labels: To review

#1280 Mise à jour du MCD
  docs/adr/002_mcd.md
Labels: tech, To review

#1281 Update MCD
  docs/adr/002_mcd.md
Labels: To review

#1282 Emails reset password soft bounce
  tests/Integration/Infrastructure/Controller/Security/ForgotPasswordControllerTest.php
  translations/emails.fr.xlf
Labels: To review, Critique

#1283 Remplit le createdAt dans l'admin d'Organization
  src/Infrastructure/Controller/Admin/OrganizationCrudController.php
Labels: To review

#1270 Add regulation order template
  assets/controllers/rich_text_controller.js
  assets/styles/quill.css
  config/validator/Application/Organization/RegulationOrderTemplate/SaveRegulationOrderTemplateCommand.xml
  package-lock.json
  package.json
  src/Application/Regulation/Command/RegulationOrderTemplate/SaveRegulationOrderTemplateCommand.php
  src/Application/Regulation/Command/RegulationOrderTemplate/SaveRegulationOrderTemplateCommandHandler.php
  src/Domain/Regulation/DefaultRegulationOrderTemplateContent.php
  src/Domain/Regulation/RegulationOrderTemplate.php
  src/Domain/Regulation/Repository/RegulationOrderTemplateRepositoryInterface.php
  src/Infrastructure/Controller/MyArea/Organization/RegulationOrderTemplate/AddRegulationOrderTemplateController.php
  src/Infrastructure/Form/Organization/RegulationOrderTemplateFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderTemplateRepository.php
  templates/my_area/organization/regulation_order_template/form.html.twig
  templates/my_area/organization/regulation_order_template/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/RegulationOrderTemplate/AddRegulationOrderTemplateControllerTest.php
  tests/Unit/Application/Regulation/Command/RegulationOrderTemplate/SaveRegulationOrderTemplateCommandHandlerTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTemplateTest.php
  translations/messages.fr.xlf
  webpack.config.js
Labels: To review

#1276 Ajoute une documentation sur le processus d'intégration de données
  docs/public/integration.md
Labels: To review

#1290 Enable gzip compression
  paas/server.locations
Labels: To review

#1289 Edit regulation order template
  assets/controllers/rich_text_controller.js
  src/Application/Regulation/Query/RegulationOrderTemplate/GetRegulationOrderTemplateQuery.php
  src/Application/Regulation/Query/RegulationOrderTemplate/GetRegulationOrderTemplateQueryHandler.php
  src/Domain/Regulation/Repository/RegulationOrderTemplateRepositoryInterface.php
  src/Infrastructure/Controller/MyArea/Organization/RegulationOrderTemplate/EditRegulationOrderTemplateController.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderTemplateRepository.php
  templates/my_area/organization/regulation_order_template/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/RegulationOrderTemplate/EditRegulationOrderTemplateControllerTest.php
  tests/Unit/Application/Regulation/Query/RegulationOrderTemplate/GetRegulationOrderTemplateQueryHandlerTest.php
Labels: To review

#1287 Màj déclaration écoconception mars-avril 2025
  assets/styles/components/landing.css
  public/files/2025-03-06 - Déclaration écoconception DiaLog - Détail.pdf
  public/files/2025-04-23 - Déclaration écoconception DiaLog.pdf
  templates/ecodesign_statement.html.twig
  tests/Integration/Infrastructure/Controller/EcodesignStatementControllerTest.php
Labels: To review

#1295 Détail arrêté : applique nouvelle maquette pour la sidebar
  assets/styles/components/dsfr-extensions/icon.scss
  public/images/icons/file-copy-line.svg
  templates/my_area/organization/visa_model/index.html.twig
  templates/regulation/_regulation_order_history.html.twig
  templates/regulation/_status_badge.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_export_section.html.twig
  templates/regulation/fragments/_measure.html.twig
  templates/regulation/fragments/_publication_button.html.twig
Labels: UI / UX, To review

#1296 Liste des arrêtés : conserve l'état des filtres après une suppression
  src/Infrastructure/Controller/Regulation/DeleteRegulationController.php
  templates/regulation/_items.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/DeleteRegulationControllerTest.php
Labels: To review

#1297 Ajout d'un colonne 'a été contacté' au feedback
  src/Domain/User/Feedback.php
  src/Infrastructure/Controller/Admin/FeedbackCrudController.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Feedback.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250429100208.php
  tests/Unit/Domain/User/FeedbackTest.php
Labels: To review

#1298 Sort feedback by creation date
  src/Infrastructure/Controller/Admin/FeedbackCrudController.php
Labels: To review

#1299 Corrige erreur 500 lors suppression de 2+ localisations
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/UpdateMeasureControllerTest.php
Labels: Bug, To review
