Repository MTES-MCT/dialog, pull requests merged in 2025-01, with the labels that each got.

#1128 Update to Symfony 7.2.2
  composer.lock
  package-lock.json
Labels: To review

#1129 Corrige ci_metabase_export
  .github/workflows/metabase_export.yml
  Makefile
Labels: Bug, To review

#1130 Correction valeur tonnage dans la dropdowm
  src/Infrastructure/Form/Regulation/VehicleSetFormType.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/AddMeasureControllerTest.php
Labels: Bug

#1125 Améliorations de la modale localisation
  templates/regulation/fragments/_measure_form.html.twig
  translations/messages.fr.xlf
Labels: To review

#1134 Corrige l'export Metabase : DATABASE_URL manquant, uuid d'utilisateur actif incorrect
  Makefile
  docs/tools/metabase.md
  src/Infrastructure/Persistence/Doctrine/Repository/Statistics/StatisticsRepository.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/UserRepository.php
  tests/Integration/Infrastructure/Symfony/Command/RunMetabaseExportCommandTest.php
Labels: Bug, To review

#1135 Ajuste la page stats pour le nouveau dashboard Metabase
  src/Application/Regulation/Query/GetStatisticsQuery.php
  src/Application/Regulation/Query/GetStatisticsQueryHandler.php
  src/Infrastructure/Controller/StatisticsController.php
  templates/statistics.html.twig
  tests/Integration/Infrastructure/Controller/StatisticsControllerTest.php
  tests/Unit/Application/Regulation/Query/GetStatisticsQueryHandlerTest.php
Labels: To review

#1144 Désactive la navigation JS (Turbo Drive) par défaut
  assets/bootstrap.js
Labels: UI / UX, tech, To review

#1145 User model refacto
  src/Application/User/Command/ConvertAccessRequestToUserCommandHandler.php
  src/Application/User/Command/SaveOrganizationUserCommandHandler.php
  src/Application/User/Command/SavePasswordCommandHandler.php
  src/Domain/User/PasswordUser.php
  src/Domain/User/ProConnectUser.php
  src/Domain/User/Repository/PasswordUserRepositoryInterface.php
  src/Domain/User/User.php
  src/Infrastructure/Controller/MyArea/Profile/EditPasswordController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/UserFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.PasswordUser.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/User.ProConnectUser.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/User.User.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250113103218.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/PasswordUserRepository.php
  src/Infrastructure/Security/Provider/UserProvider.php
  tests/Unit/Application/User/Command/ConvertAccessRequestToUserCommandHandlerTest.php
  tests/Unit/Application/User/Command/SaveOrganizationUserCommandHandlerTest.php
  tests/Unit/Application/User/Command/SavePasswordCommandHandlerTest.php
  tests/Unit/Domain/User/PasswordUserTest.php
  tests/Unit/Domain/User/ProConnectUserTest.php
  tests/Unit/Domain/User/UserTest.php
Labels: To review

#1139 Affiche plus de détails dans le rapport Litteralis
  src/Infrastructure/IntegrationReport/CommonRecordEnum.php
  src/Infrastructure/IntegrationReport/ReportFormatter.php
  src/Infrastructure/Litteralis/LitteralisExecutor.php
  src/Infrastructure/Litteralis/LitteralisExtractor.php
  src/Infrastructure/Litteralis/LitteralisPeriodParser.php
  src/Infrastructure/Litteralis/LitteralisTransformer.php
  tests/Integration/Infrastructure/IntegrationReport/ReportFormatterTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExecutorTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExtractorTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisPeriodParserTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisTransformerTest.php
Labels: To review

#1151 [Carte] N'affiche aucune restriction quand ni Permanent ni Temporaire ne sont cochés
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  tests/Integration/Infrastructure/Controller/Map/Fragment/MapDataControllerTest.php
Labels: Bug, To review

#1150 Exporte le nombre d'incidents CIFS dans Metabase
  .env
  .github/workflows/metabase_export.yml
  config/packages/framework.yaml
  config/services.yaml
  docs/tools/metabase.md
  src/Application/Cifs/CifsExportClientInterface.php
  src/Infrastructure/Adapter/CifsExportClient.php
  src/Infrastructure/Persistence/Doctrine/Repository/Statistics/StatisticsRepository.php
  tests/Integration/Infrastructure/Symfony/Command/RunMetabaseExportCommandTest.php
  tests/Mock/DiaLogMockHttpClient.php
  tests/Unit/Infrastructure/Adapter/CifsExportClientTest.php
Labels: To review

#1146 Rassemble les intégrations Litteralis en une seule
  .env
  .env.test
  .github/workflows/litteralis_fougeres_import.yml
  .github/workflows/litteralis_import.yml
  .github/workflows/litteralis_mel_import.yml
  Makefile
  config/services.yaml
  docs/tools/litteralis.md
  src/Application/Litteralis/DTO/LitteralisCredentials.php
  src/Infrastructure/IntegrationReport/Reporter.php
  src/Infrastructure/Litteralis/Fougeres/FougeresExecutor.php
  src/Infrastructure/Litteralis/LitteralisClient.php
  src/Infrastructure/Litteralis/LitteralisClientFactory.php
  src/Infrastructure/Litteralis/LitteralisExecutor.php
  src/Infrastructure/Litteralis/LitteralisExtractor.php
  src/Infrastructure/Litteralis/LonsLeSaunier/LonsLeSaunierExecutor.php
  src/Infrastructure/Litteralis/MEL/MELExecutor.php
  src/Infrastructure/Symfony/Command/FougeresImportCommand.php
  src/Infrastructure/Symfony/Command/LitteralisImportCommand.php
  src/Infrastructure/Symfony/Command/LonsLeSaunierImportCommand.php
  src/Infrastructure/Symfony/Command/MELImportCommand.php
  src/Infrastructure/Symfony/Command/MELRegulationGetCommand.php
  src/Infrastructure/Symfony/DependencyInjection/LitteralisCredentialsEnvVarProcessor.php
  tests/Integration/Infrastructure/Symfony/Command/LitteralisImportCommandTest.php
  tests/Integration/Infrastructure/Symfony/Command/LonsLeSaunierImportCommandTest.php
  tests/Integration/Infrastructure/Symfony/Command/MELImportCommandTest.php
  tests/Integration/Infrastructure/Symfony/Command/MELRegulationGetCommandTest.php
  tests/Unit/Application/Litteralis/DTO/LitteralisCredentialsTest.php
  tests/Unit/Infrastructure/IntegrationReport/ReporterTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExecutorTest.php
  tests/Unit/Infrastructure/Litteralis/LitteralisExtractorTest.php
  tests/Unit/Infrastructure/Symfony/Command/FougeresImportCommandTest.php
  tests/Unit/Infrastructure/Symfony/Command/LitteralisImportCommandTest.php
  tests/Unit/Infrastructure/Symfony/Command/LonsLeSaunierImportCommandTest.php
  tests/Unit/Infrastructure/Symfony/Command/MELImportCommandTest.php
  tests/Unit/Infrastructure/Symfony/DependencyInjection/LitteralisCredentialsEnvVarProcessorTest.php
  tools/ci_litteralis_init_org_env_vars.py
Labels: To review

#1154 Fix Litteralis Import : "A value containing spaces must be surrounded by quotes
  .github/workflows/litteralis_import.yml
Labels: To review

#1158 Ajout du modèle de donnée Token
  src/Domain/User/Enum/TokenTypeEnum.php
  src/Domain/User/Token.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Token.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250121142614.php
  tests/Unit/Domain/User/TokenTest.php
Labels: To review

#1156 Corrige le catch-all dans LitteralisImportCommand
  src/Infrastructure/Symfony/Command/LitteralisImportCommand.php
  tests/Unit/Infrastructure/Symfony/Command/LitteralisImportCommandTest.php
Labels: Bug, To review

#1153 Fix Metabase export CI : variables -> vars
  .github/workflows/metabase_export.yml
Labels: To review

#1161 Suppression de la fonctionnalité feature flag
  src/Infrastructure/FeatureFlagService.php
  src/Infrastructure/Twig/AppExtension.php
  tests/Unit/Infrastructure/FeatureFlagServiceTest.php
  tests/Unit/Infrastructure/Twig/AppExtensionTest.php
Labels: tech, To review

#1157 [Litteralis] Corrige bug si paramètre mesures mal formaté
  src/Infrastructure/Litteralis/LitteralisRecordEnum.php
  src/Infrastructure/Litteralis/LitteralisTransformer.php
  tests/Unit/Infrastructure/Litteralis/LitteralisTransformerTest.php
  translations/messages.fr.xlf
Labels: Bug, To review

#1160 Configuration du mailer + messages asynchrones
  .env
  Makefile
  Procfile
  composer.json
  composer.lock
  config/packages/mailer.yaml
  config/packages/messenger.yaml
  docker-compose.yml
  docker/php/Dockerfile
  docker/php/supervisor/conf.d/messenger-worker.conf
  docker/php/supervisor/supervisord.conf
  docs/tools/README.md
  docs/tools/mailer.md
  docs/tools/redis.md
  src/Application/AsyncCommandInterface.php
  src/Application/CommandBusInterface.php
  src/Infrastructure/Adapter/CommandBus.php
  symfony.lock
Labels: To review

#1168 Traite l'obsolescence de actions/upload-artifact@v3
  .github/workflows/ci.yml
  .github/workflows/eudonet_paris_import.yml
  .github/workflows/litteralis_import.yml
Labels: To review, Significatif

#1147 Traçabilité des modifications sur un arrêté
  src/Application/Regulation/Command/CreateRegulationOrderHistoryCommand.php
  src/Application/Regulation/Command/CreateRegulationOrderHistoryCommandHandler.php
  src/Application/Regulation/Command/DeleteRegulationCommandHandler.php
  src/Application/Regulation/Command/PublishRegulationCommandHandler.php
  src/Application/Regulation/Command/SaveRegulationGeneralInfoCommandHandler.php
  src/Domain/Regulation/Enum/ActionTypeEnum.php
  src/Domain/Regulation/RegulationOrderHistory.php
  src/Domain/Regulation/Repository/RegulationOrderHistoryRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.RegulationOrderHistory.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250116114330.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/RegulationOrderHistoryRepository.php
  tests/Unit/Application/Regulation/Command/CreateRegulationOrderHistoryCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/DeleteRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/PublishRegulationCommandHandlerTest.php
  tests/Unit/Application/Regulation/Command/SaveRegulationGeneralInfoCommandHandlerTest.php
  tests/Unit/Domain/Regulation/RegulationOrderHistoryTest.php
Labels: To review

#1152 [Carte] Corrige la prise en compte des heures dans les filtres de période d'application
  src/Infrastructure/Persistence/Doctrine/Fixtures/LocationFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/PeriodFixture.php
  src/Infrastructure/Persistence/Doctrine/Repository/Regulation/LocationRepository.php
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Integration/Infrastructure/Controller/Map/Fragment/GetLocationControllerTest.php
  tests/Integration/Infrastructure/Controller/Map/Fragment/MapDataControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/Fragments/GetMeasureControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/ListRegulationsControllerTest.php
Labels: Bug, To review

#1171 Reactive Turbo Drive
  assets/bootstrap.js
Labels: Bug, Significatif

#1164 Ajoute l'entité StorageArea
  data/aires_de_stockage.csv
  src/Domain/Regulation/Location/Location.php
  src/Domain/Regulation/Location/StorageArea.php
  src/Domain/Regulation/Repository/StorageAreaRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Location.Location.orm.xml
  src/Infrastructure/Persistence/Doctrine/Mapping/Regulation.Location.StorageArea.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250123102525.php
  tests/Unit/Domain/Regulation/Location/LocationTest.php
  tests/Unit/Domain/Regulation/Location/StorageAreaTest.php
Labels: To review

#1172 Retire les method=DELETE non-standards
  config/packages/framework.yaml
  templates/my_area/organization/logo.html.twig
  templates/my_area/organization/user/index.html.twig
  templates/my_area/organization/visa_model/index.html.twig
  templates/my_area/profile/delete-profile.html.twig
  templates/regulation/_items.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/fragments/_measure_delete_form.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
Labels: tech, To review

#1178 Update to Symfony 7.3.3
  composer.lock
  package-lock.json
Labels: tech, To review

#1165 Ajout de la fonctionnalité mot de passe oublié
  .env
  .github/workflows/ci.yml
  Makefile
  composer.json
  composer.lock
  config/packages/twig.yaml
  config/validator/Application/User/Mail/SendForgotPasswordMailCommand.xml
  config/validator/Application/User/ResetPasswordCommand.xml
  docker-compose.yml
  docker/php/Dockerfile
  docker/php/supervisor/supervisord.conf
  docs/tools/redis.md
  public/images/logo_email.png
  src/Application/MailerInterface.php
  src/Application/User/Command/CreateTokenCommandHandler.php
  src/Application/User/Command/Mail/SendForgotPasswordMailCommand.php
  src/Application/User/Command/Mail/SendForgotPasswordMailCommandHandler.php
  src/Application/User/Command/ResetPasswordCommand.php
  src/Application/User/Command/ResetPasswordCommandHandler.php
  src/Domain/Mail.php
  src/Domain/User/Exception/TokenExpiredException.php
  src/Domain/User/Exception/TokenNotFoundException.php
  src/Domain/User/Specification/IsTokenExpired.php
  src/Infrastructure/Adapter/Mailer.php
  src/Infrastructure/Controller/Security/ForgotPasswordController.php
  src/Infrastructure/Controller/Security/ResetPasswordController.php
  src/Infrastructure/Form/User/ForgotPasswordFormType.php
  src/Infrastructure/Form/User/ResetPasswordFormType.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/TokenFixture.php
  symfony.lock
  templates/email/base.html.twig
  templates/email/user/forgot_password.html.twig
  templates/forgot_password.html.twig
  templates/layouts/layout.html.twig
  templates/reset_password.html.twig
  tests/Integration/Infrastructure/Controller/AbstractWebTestCase.php
  tests/Integration/Infrastructure/Controller/Security/ForgotPasswordControllerTest.php
  tests/Integration/Infrastructure/Controller/Security/ResetPasswordControllerTest.php
  tests/Unit/Application/User/Command/CreateTokenCommandHandlerTest.php
  tests/Unit/Application/User/Command/Mail/SendForgotPasswordMailCommandHandlerTest.php
  tests/Unit/Application/User/Command/ResetPasswordCommandHandlerTest.php
  tests/Unit/Domain/User/Specification/IsTokenExpiredTest.php
  translations/emails.fr.xlf
  translations/messages.fr.xlf
Labels: To review

#1180 Fix worker option
  Procfile
Labels: Bug

#1177 Ajoute le lien vers gitbook dans la barre de navigation
  templates/layouts/layout.html.twig
  tests/Integration/Infrastructure/Controller/LandingControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1175 Gère les géométries Litteralis déjà sous forme de linéaires
  src/Infrastructure/Adapter/BdTopoRoadGeocoder.php
  src/Infrastructure/Integration/Litteralis/LitteralisTransformer.php
  tests/Integration/Infrastructure/Adapter/BdTopoRoadGeocoderTest.php
Labels: Bug, To review, Significatif

#1183 Fix exported logo size
  templates/regulation/export.md.twig
Labels: UI / UX, To review

#1179 Active user account
  config/packages/security.yaml
  src/Application/User/Command/ConfirmAccountCommand.php
  src/Application/User/Command/ConfirmAccountCommandHandler.php
  src/Application/User/Command/Mail/SendConfirmationMailCommand.php
  src/Application/User/Command/Mail/SendConfirmationMailCommandHandler.php
  src/Application/User/Command/SaveOrganizationUserCommandHandler.php
  src/Domain/User/User.php
  src/Infrastructure/Controller/Security/ConfirmAccountController.php
  src/Infrastructure/Controller/Security/RegisterController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/TokenFixture.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/UserFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.User.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250128103955.php
  src/Infrastructure/Security/Provider/UserProvider.php
  src/Infrastructure/Security/SymfonyUser.php
  src/Infrastructure/Security/UserChecker.php
  templates/email/user/confirm_user_account.html.twig
  templates/email/user/forgot_password.html.twig
  tests/Integration/Infrastructure/Controller/Security/ConfirmAccountControllerTest.php
  tests/Integration/Infrastructure/Controller/Security/LoginControllerTest.php
  tests/Integration/Infrastructure/Controller/Security/RegisterControllerTest.php
  tests/Unit/Application/User/Command/ConfirmAccountCommandHandlerTest.php
  tests/Unit/Application/User/Command/Mail/SendConfirmationMailCommandHandlerTest.php
  tests/Unit/Application/User/Command/SaveOrganizationUserCommandHandlerTest.php
  tests/Unit/Domain/User/UserTest.php
  tests/Unit/Infrastructure/Security/SymfonyUserTest.php
  tests/Unit/Infrastructure/Security/UserCheckerTest.php
  translations/emails.fr.xlf
  translations/messages.fr.xlf
Labels: To review

#1182 Empêche le redémarrage normal du prod de déclencher un crash Scalingo
  Procfile
Labels: Bug, tech

#1166 Ajoute et execute l'outil d'import des aires de stockage
  Makefile
  composer.json
  composer.lock
  data/.gitignore
  docs/tools/storage_areas.md
  src/Infrastructure/Data/StorageArea/StorageAreaMigrationGenerator.php
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250128104726.php
  src/Infrastructure/Symfony/Command/StorageAreaGenerateCommand.php
  tests/Integration/Infrastructure/Symfony/Command/StorageAreaGenerateCommandTest.php
  tests/Unit/Infrastructure/Data/StorageArea/StorageAreaMigrationGeneratorTest.php
  tests/fixtures/aires_de_stockage_test.csv
Labels: To review

#1185 Purge user tokens
  composer.lock
  cron.json
  package-lock.json
  src/Domain/User/Repository/TokenRepositoryInterface.php
  src/Infrastructure/Persistence/Doctrine/Repository/User/TokenRepository.php
  src/Infrastructure/Symfony/Command/PurgeUserTokensCommand.php
  tests/Integration/Infrastructure/Symfony/Command/PurgeUserTokensCommandTest.php
Labels: To review
