Repository MTES-MCT/dialog, pull requests merged in 2025-05, with the labels that each got.

#1273 Add mailing list
  config/validator/Application/Organization/Logo/MailingList/SaveMailingListCommand.xml
  src/Application/Organization/MailingList/Command/DeleteMailingListCommand.php
  src/Application/Organization/MailingList/Command/DeleteMailingListCommandHandler.php
  src/Application/Organization/MailingList/Command/SaveMailingListCommand.php
  src/Application/Organization/MailingList/Command/SaveMailingListCommandHandler.php
  src/Application/Organization/MailingList/Query/GetRecipientQuery.php
  src/Application/Organization/MailingList/Query/GetRecipientQueryHandler.php
  src/Domain/Organization/MailingList/Exception/MailingListNotFoundException.php
  src/Domain/Organization/MailingList/MailingList.php
  src/Domain/Organization/MailingList/Repository/MailingListRepositoryInterface.php
  src/Infrastructure/Controller/MyArea/Organization/MailingList/AddRecipientsListController.php
  src/Infrastructure/Controller/MyArea/Organization/MailingList/DeleteRecipientController.php
  src/Infrastructure/Controller/MyArea/Organization/MailingList/EditRecipientController.php
  src/Infrastructure/Form/Organization/MailingListFormType.php
  src/Infrastructure/Persistence/Doctrine/Repository/MailingList/MailingListRepository.php
  templates/my_area/organization/_menu.html.twig
  templates/my_area/organization/mailing_list/form.html.twig
  templates/my_area/organization/mailing_list/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/MailingList/AddRecipientsListControllerTest.php
  tests/Integration/Infrastructure/Controller/MyArea/Organization/MailingList/DeleteRecipientControllerTest.php
  tests/Integration/Infrastructure/Controller/MyArea/Organization/MailingList/EditRecipientControllerTest.php
  tests/Integration/Infrastructure/Controller/MyArea/Organization/MailingList/RecipientsListControllerTest.php
  tests/Unit/Application/Organization/MailingList/Command/DeleteMailingListCommandHandlerTest.php
  tests/Unit/Application/Organization/MailingList/Command/SaveMailingListCommandHandlerTest.php
  tests/Unit/Application/Organization/MailingList/Query/GetRecipientQueryHandlerTest.php
  tests/Unit/Domain/MailingList/MailingListTest.php
  translations/messages.fr.xlf
Labels: To review

#1309 Récupération des nom/code d'un département
  src/Application/Organization/Command/GetOrCreateOrganizationBySiretCommandHandler.php
  src/Application/Organization/View/OrganizationFetchedView.php
  src/Domain/User/Organization.php
  src/Infrastructure/Adapter/ApiOrganizationFetcher.php
  src/Infrastructure/Controller/Admin/OrganizationCrudController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/OrganizationFixture.php
  src/Infrastructure/Persistence/Doctrine/Mapping/User.Organization.orm.xml
  src/Infrastructure/Persistence/Doctrine/Migrations/Version20250506144832.php
  src/Infrastructure/Symfony/Command/SyncOrganizationsCodesCommand.php
  tests/Integration/Infrastructure/Controller/Api/get-regulations-expected-result.xml
  tests/Mock/ApiGeoMock.php
  tests/Mock/ApiOrganizationFetcherMock.php
  tests/Unit/Application/Organization/Command/GetOrCreateOrganizationBySiretCommandHandlerTest.php
  tests/Unit/Domain/User/OrganizationTest.php
  tests/Unit/Infrastructure/Adapter/ApiOrganizationFetcherTest.php
Labels: To review

#1314 Add spam notice
  tests/Integration/Infrastructure/Controller/Security/ForgotPasswordControllerTest.php
  translations/messages.fr.xlf
Labels: To review

#1318 Duplicate regulation order template
  src/Application/Regulation/Command/RegulationOrderTemplate/DuplicateRegulationOrderTemplateCommand.php
  src/Application/Regulation/Command/RegulationOrderTemplate/DuplicateRegulationOrderTemplateCommandHandler.php
  src/Infrastructure/Controller/MyArea/Organization/RegulationOrderTemplate/DuplicateRegulationOrderTemplateController.php
  templates/my_area/organization/regulation_order_template/index.html.twig
  tests/Integration/Infrastructure/Controller/MyArea/Organization/RegulationOrderTemplate/DuplicateRegulationOrderTemplateControllerTest.php
  tests/Unit/Application/Regulation/Command/RegulationOrderTemplate/DuplicateRegulationOrderTemplateCommandHandlerTest.php
  translations/messages.fr.xlf
Labels: To review

#1319 CI Litteralis : Corrige cas des mdp avec apostrophe
  tools/ci_litteralis_init_org_env_vars.py
Labels: Bug, Critique

#1288 Adaptation du code Litteralis pour la Corrèze (aka CD19)
  src/Infrastructure/Integration/IntegrationReport/ReportFormatter.php
  src/Infrastructure/Integration/Litteralis/LitteralisExtractor.php
  src/Infrastructure/Integration/Litteralis/LitteralisPeriodParser.php
  src/Infrastructure/Integration/Litteralis/LitteralisTransformer.php
  tests/Integration/Infrastructure/IntegrationReport/ReportFormatterTest.php
  tests/Unit/Infrastructure/Integration/Litteralis/LitteralisExtractorTest.php
  tests/Unit/Infrastructure/Integration/Litteralis/LitteralisTransformerTest.php
  translations/messages.fr.xlf
Labels: To review

#1325 Corrige mauvais typage getSubject()
  src/Domain/Regulation/RegulationOrder.php
  tests/Unit/Domain/Regulation/RegulationOrderTest.php
Labels: Bug, To review

#1322 Add regulation order template to super admin
  src/Application/Regulation/Command/RegulationOrderTemplate/SaveRegulationOrderTemplateCommandHandler.php
  src/Domain/Regulation/RegulationOrderTemplate.php
  src/Infrastructure/Controller/Admin/DashboardController.php
  src/Infrastructure/Controller/Admin/RegulationOrderTemplateCrudController.php
  src/Infrastructure/Persistence/Doctrine/Fixtures/RegulationOrderTemplateFixture.php
  templates/admin/form.html.twig
  tests/Integration/Infrastructure/Controller/Admin/RegulationOrderTemplateCrudControllerTest.php
  tests/Unit/Application/Regulation/Command/RegulationOrderTemplate/SaveRegulationOrderTemplateCommandHandlerTest.php
  tests/Unit/Domain/Regulation/RegulationOrderTemplateTest.php
Labels: To review

#1327 Suppression de la possibilité de modifier un modèle générique
  templates/my_area/organization/regulation_order_template/index.html.twig
Labels: To review

#1328 Supprime une option inutile du rich text editor
  assets/controllers/rich_text_controller.js
Labels: To review

#1303 Envoi du template mail à la liste de diffusion
  config/validator/Application/Regulation/Command/SendRegulationOrderToMailingListCommand.xml
  public/images/logo_email.png
  public/images/logo_email.webp
  src/Application/Organization/MailingList/Command/SendRegulationOrderToMailingListCommand.php
  src/Application/Organization/MailingList/Command/SendRegulationOrderToMailingListCommandHandler.php
  src/Infrastructure/Controller/Regulation/SendRegulationOrderToMailingListController.php
  src/Infrastructure/Form/Organization/SendToMailingListFormType.php
  src/Infrastructure/Validator/EmailsConstraint.php
  src/Infrastructure/Validator/EmailsConstraintValidator.php
  templates/email/base.html.twig
  templates/email/mailing_list/mailing_list_email.html.twig
  templates/regulation/detail.html.twig
  templates/regulation/send_to_mailing_list.html.twig
  tests/Integration/Infrastructure/Controller/Regulation/RegulationDetailControllerTest.php
  tests/Integration/Infrastructure/Controller/Regulation/SendRegulationOrderToMailingListControllerTest.php
  tests/Unit/Application/Organization/MailingList/Command/SendRegulationOrderToMailingListCommandHandlerTest.php
  translations/emails.fr.xlf
  translations/messages.fr.xlf
  translations/validators.fr.xlf
Labels: To review
